// jikan-frontend/src/routes/movies/+page.svelte
<script lang="ts">
  import { api } from "$lib/api";
  import AnimeCard from "$lib/components/AnimeCard.svelte";
  import { onMount } from "svelte";

  let items: any[] = $state([]);
  let loading = $state(true);
  let hasNext = $state(false);
  let currentPage = $state(1);

  onMount(() => loadPage(1));

  async function loadPage(p: number) {
    loading = true;
    try {
      const res = await api.getTopAnime("MOVIE", p);
      items = p === 1 ? res.data : [...items, ...res.data];
      hasNext = res.pagination?.has_next_page || false;
      currentPage = p;
    } catch (e) {
      console.error(e);
    } finally {
      loading = false;
    }
  }
</script>

<svelte:head><title>Movies — AnimePro</title></svelte:head>

<div class="page container">
  <h1 class="page-title">🎬 Anime Movies</h1>
  {#if loading && items.length === 0}
    <div class="center"><div class="spinner"></div></div>
  {:else}
    <div class="grid">
      {#each items as anime (anime.id)}
        <AnimeCard {anime} />
      {/each}
    </div>
    {#if hasNext}
      <div class="center">
        <button
          class="btn-secondary"
          onclick={() => loadPage(currentPage + 1)}
          disabled={loading}
        >
          {loading ? "Loading..." : "Load More"}
        </button>
      </div>
    {/if}
  {/if}
</div>

<style>
  .page {
    padding-top: 2rem;
  }
  .page-title {
    font-size: 1.8rem;
    font-weight: 700;
    margin-bottom: 1.5rem;
  }
  .grid {
    display: grid;
    gap: 1.25rem;
    grid-template-columns: repeat(auto-fill, minmax(145px, 1fr));
  }
  .center {
    display: flex;
    justify-content: center;
    padding: 2rem 0;
  }

  @media (max-width: 768px) {
    .page {
      padding-top: 1.5rem;
    }
    .page-title {
      font-size: 1.5rem;
      margin-bottom: 1.25rem;
    }
    .grid {
      gap: 1rem;
      grid-template-columns: repeat(auto-fill, minmax(120px, 1fr));
    }
    .center {
      padding: 1.5rem 0;
    }
  }

  @media (max-width: 480px) {
    .page {
      padding-top: 1rem;
    }
    .page-title {
      font-size: 1.3rem;
      margin-bottom: 1rem;
    }
    .grid {
      gap: 0.85rem;
      grid-template-columns: repeat(auto-fill, minmax(100px, 1fr));
    }
    .center {
      padding: 1.25rem 0;
    }
  }

  @media (max-width: 360px) {
    .page-title {
      font-size: 1.2rem;
    }
    .grid {
      gap: 0.7rem;
      grid-template-columns: repeat(auto-fill, minmax(90px, 1fr));
    }
  }
</style>

// jikan-frontend/src/pages/Movies.tsx
import { useEffect, useState } from 'react';
import { animeAPI, normalize } from '../api/client';
import AnimeCard from '../components/AnimeCard';
import { motion, AnimatePresence } from 'framer-motion';
import { Film, ChevronLeft, ChevronRight } from 'lucide-react';
import { PageSkeleton } from '../components/Skeleton';

const Movies = () => {
  const [animes, setAnimes] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [page, setPage] = useState(1);
  const [hasNextPage, setHasNextPage] = useState(false);

  useEffect(() => {
    const fetchMovies = async () => {
      setLoading(true);
      try {
        // Use Jikan API getTopAnime for movies
        const res = await animeAPI.getTopAnime('movie', page, 20);
        const data = res.data?.data;
        // Jikan returns data.data array
        setAnimes((data || []).map(normalize));
        // Jikan pagination info
        const pagination = res.data?.pagination;
        setHasNextPage(pagination?.has_next_page || false);
      } catch (err) {
        console.error('Failed to fetch movies', err);
      } finally {
        setLoading(false);
      }
    };
    fetchMovies();
    window.scrollTo({ top: 0, behavior: 'smooth' });
  }, [page]);

  const containerVariants = {
    hidden: { opacity: 0 },
    show: { opacity: 1, transition: { staggerChildren: 0.07 } }
  };
  const itemVariants = { hidden: { opacity: 0, y: 20 }, show: { opacity: 1, y: 0 } };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: -20 }}
      transition={{ duration: 0.4 }}
      style={{ backgroundColor: 'var(--net-bg)', minHeight: '100vh', padding: '100px 4% 4rem' }}
    >
      <header style={{ marginBottom: '2.5rem' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', marginBottom: '1rem' }}>
          <Film className="text-red" size={28} />
          <h1 style={{ fontSize: '2rem', fontWeight: 800 }}>Anime Movies</h1>
        </div>
      </header>

      {loading ? (
        <PageSkeleton />
      ) : (
        <>
          <motion.div variants={containerVariants} initial="hidden" animate="show"
            style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(180px, 1fr))', gap: '1.5rem 1rem' }}>
            <AnimatePresence mode="popLayout">
              {animes.map((anime) => (
                <motion.div key={anime.id} variants={itemVariants}>
                  <AnimeCard anime={anime} />
                </motion.div>
              ))}
            </AnimatePresence>
          </motion.div>

          {animes.length === 0 && (
            <div style={{ textAlign: 'center', padding: '4rem', color: 'var(--net-text-muted)' }}>No movies found.</div>
          )}

          <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', gap: '2rem', marginTop: '4rem' }}>
            <button disabled={page === 1} onClick={() => setPage(p => p - 1)} className="glass"
              style={{ padding: '0.75rem', borderRadius: '50%', opacity: page === 1 ? 0.3 : 1, cursor: page === 1 ? 'default' : 'pointer' }}>
              <ChevronLeft size={24} />
            </button>
            <span style={{ fontWeight: 600, fontSize: '1.1rem' }}>Page {page}</span>
            <button disabled={!hasNextPage} onClick={() => setPage(p => p + 1)} className="glass"
              style={{ padding: '0.75rem', borderRadius: '50%', opacity: !hasNextPage ? 0.3 : 1, cursor: !hasNextPage ? 'default' : 'pointer' }}>
              <ChevronRight size={24} />
            </button>
          </div>
        </>
      )}
    </motion.div>
  );
};

export default Movies;
