// anime-pro/src/components/AnimeCard.tsx
import { useState, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Play, Plus, ThumbsUp, ChevronDown } from 'lucide-react';
import { useNavigate } from 'react-router-dom';

interface AnimeCardProps {
  anime: any;
  isLargeRow?: boolean;
}

const AnimeCard: React.FC<AnimeCardProps> = ({ anime, isLargeRow }) => {
  const [isHovered, setIsHovered] = useState(false);
  const navigate = useNavigate();
  const timeoutRef = useRef<any>(null);

  const imageUrl = anime.poster || anime.image || '';
  const title = anime.title || 'Unknown Title';
  const id = anime.id;

  const handleMouseEnter = () => {
    timeoutRef.current = setTimeout(() => {
      setIsHovered(true);
    }, 400); 
  };

  const handleMouseLeave = () => {
    if (timeoutRef.current) clearTimeout(timeoutRef.current);
    setIsHovered(false);
  };

  const handleDetailClick = (e: React.MouseEvent) => {
    e.stopPropagation();
    navigate(`/anime/${id}`);
  };

  const handlePlayClick = (e: React.MouseEvent) => {
    e.stopPropagation();
    navigate(`/watch/${id}/1`);
  };

  return (
    <div 
      className="anime-card-container"
      style={{
        position: 'relative',
        width: isLargeRow ? '160px' : '240px',
        height: isLargeRow ? '240px' : '135px',
        cursor: 'pointer',
        flexShrink: 0,
        zIndex: isHovered ? 100 : 1
      }}
      onMouseEnter={handleMouseEnter}
      onMouseLeave={handleMouseLeave}
      onClick={handleDetailClick}
    >
      <motion.img 
        src={imageUrl} 
        alt={title}
        style={{
          width: '100%',
          height: '100%',
          objectFit: 'cover',
          borderRadius: '4px'
        }}
        whileHover={{ scale: 1.05 }}
      />
      
      <AnimatePresence>
        {isHovered && (
          <motion.div
            initial={{ opacity: 0, scale: 0.9, y: 0 }}
            animate={{ opacity: 1, scale: 1.25, y: -20 }}
            exit={{ opacity: 0, scale: 0.9, y: 0 }}
            transition={{ duration: 0.3, ease: "easeOut" }}
            style={{
              position: 'absolute',
              top: 0,
              left: 0,
              width: '100%',
              backgroundColor: 'var(--net-card-bg)',
              borderRadius: '8px',
              boxShadow: '0 12px 30px rgba(0,0,0,0.8)',
              zIndex: 110,
              overflow: 'hidden'
            }}
          >
            <div style={{ position: 'relative', height: '140px' }}>
              <img 
                src={imageUrl} 
                alt={title} 
                style={{ width: '100%', height: '100%', objectFit: 'cover' }} 
              />
              <div style={{
                position: 'absolute',
                top: 0, left: 0, right: 0, bottom: 0,
                background: 'linear-gradient(to top, var(--net-card-bg) 0%, transparent 50%)'
              }} />
            </div>

            <div style={{ padding: '0.8rem' }}>
              <div style={{ display: 'flex', gap: '8px', marginBottom: '12px' }}>
                <button 
                  onClick={handlePlayClick}
                  className="btn-primary"
                  style={{ borderRadius: '50%', width: '32px', height: '32px', padding: 0, justifyContent: 'center' }}
                >
                  <Play fill="black" size={16} />
                </button>
                <button style={{ border: '2px solid rgba(255,255,255,0.4)', borderRadius: '50%', width: '32px', height: '32px', display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'white' }}>
                  <Plus size={16} />
                </button>
                <button style={{ border: '2px solid rgba(255,255,255,0.4)', borderRadius: '50%', width: '32px', height: '32px', display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'white' }}>
                  <ThumbsUp size={16} />
                </button>
                <button 
                  onClick={handleDetailClick}
                  style={{ marginLeft: 'auto', border: '2px solid rgba(255,255,255,0.4)', borderRadius: '50%', width: '32px', height: '32px', display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'white' }}
                >
                  <ChevronDown size={18} />
                </button>
              </div>
              
              <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '6px' }}>
                <span style={{ color: '#46d369', fontWeight: 700, fontSize: '0.85rem' }}>98% Match</span>
                <span style={{ border: '1px solid rgba(255,255,255,0.4)', padding: '0 5px', fontSize: '0.65rem', color: 'white', borderRadius: '2px' }}>HD</span>
                {anime.isDub && <span className="bg-red" style={{ fontSize: '0.65rem', padding: '1px 5px', borderRadius: '2px', fontWeight: 700 }}>DUB</span>}
              </div>
              
              <h4 className="line-clamp-1" style={{ fontSize: '0.9rem', fontWeight: 700, color: 'white', margin: '4px 0' }}>
                {title}
              </h4>
              
              <div style={{ color: 'var(--net-text-muted)', fontSize: '0.75rem', marginTop: '4px' }}>
                Action • Sci-Fi • Thriller
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
};

export default AnimeCard;

// sveltekit-frontend/src/lib/components/AnimeCard.svelte
<script lang="ts">
  let { anime, size = "normal" } = $props<{
    anime: any;
    size?: "small" | "normal" | "large";
  }>();

  const poster = $derived(
    anime?.poster || anime?.image || anime?.images?.jpg?.large_image_url || "",
  );
  const title = $derived(anime?.title || anime?.title_english || "Unknown");
  const score = $derived(anime?.score || anime?.rating || 0);
  const id = $derived(anime?.id || anime?.mal_id);
</script>

<a
  href="/anime/{id}"
  class="card"
  class:small={size === "small"}
  class:large={size === "large"}
>
  <div class="card-img-wrap">
    <img src={poster} alt={title} loading="lazy" />
    <div class="card-overlay">
      <div class="card-play">▶</div>
    </div>
    {#if score > 0}
      <span class="card-score">⭐ {score.toFixed(1)}</span>
    {/if}
  </div>
  <p class="card-title">{title}</p>
</a>

<style>
  .card {
    display: block;
    flex-shrink: 0;
    width: 160px;
    transition: transform 0.3s ease;
    cursor: pointer;
  }
  .card:hover {
    transform: scale(1.08);
    z-index: 2;
  }
  .card.small {
    width: 130px;
  }
  .card.large {
    width: 200px;
  }
  .card-img-wrap {
    position: relative;
    border-radius: var(--radius-lg);
    overflow: hidden;
    aspect-ratio: 2 / 3;
    background: var(--net-card-bg);
  }
  .card-img-wrap img {
    width: 100%;
    height: 100%;
    object-fit: cover;
  }
  .card-overlay {
    position: absolute;
    inset: 0;
    background: rgba(0, 0, 0, 0.5);
    display: flex;
    align-items: center;
    justify-content: center;
    opacity: 0;
    transition: opacity 0.3s;
  }
  .card:hover .card-overlay {
    opacity: 1;
  }
  .card-play {
    width: 44px;
    height: 44px;
    border-radius: 50%;
    background: rgba(229, 9, 20, 0.9);
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 1.2rem;
    color: white;
  }
  .card-score {
    position: absolute;
    top: 6px;
    right: 6px;
    background: rgba(0, 0, 0, 0.75);
    color: #fbbf24;
    font-size: 0.7rem;
    padding: 2px 6px;
    border-radius: 4px;
    font-weight: 600;
  }
  .card-title {
    margin-top: 0.5rem;
    font-size: 0.85rem;
    font-weight: 500;
    color: var(--net-text-muted);
    display: -webkit-box;
    -webkit-line-clamp: 2;
    -webkit-box-orient: vertical;
    overflow: hidden;
  }
  .card:hover .card-title {
    color: white;
  }

  @media (max-width: 768px) {
    .card {
      width: 120px;
    }
    .card.small {
      width: 100px;
    }
    .card.large {
      width: 150px;
    }
    .card-title {
      font-size: 0.8rem;
    }
    .card-play {
      width: 36px;
      height: 36px;
      font-size: 1rem;
    }
    .card-score {
      font-size: 0.65rem;
      padding: 1px 4px;
    }
  }

  @media (max-width: 480px) {
    .card {
      width: 100px;
    }
    .card.small {
      width: 85px;
    }
    .card.large {
      width: 120px;
    }
    .card-title {
      font-size: 0.75rem;
    }
    .card-play {
      width: 32px;
      height: 32px;
      font-size: 0.9rem;
    }
    .card-score {
      font-size: 0.6rem;
      padding: 1px 3px;
      top: 4px;
      right: 4px;
    }
  }
</style>
