// jikan-frontend/src/components/Navbar.tsx
import React, { useState, useEffect, useRef } from 'react';
import { Link, useNavigate, useLocation } from 'react-router-dom';
import { Search, Bell, User, X, Loader2, Heart, History as HistoryIcon, LogOut, ChevronDown, Menu, Home, Clock, Film, Tv, Calendar } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { animeAPI } from '../api/client';
import { useAuth } from '../contexts/AuthContext';
import { AuthModal } from './AuthModal';

const Navbar = () => {
  const [isScrolled, setIsScrolled] = useState(false);
  const [isHidden, setIsHidden] = useState(false);
  const lastScrollY = useRef(0);
  const [searchQuery, setSearchQuery] = useState('');
  const [searchOpen, setSearchOpen] = useState(false);
  const [suggestions, setSuggestions] = useState<any[]>([]);
  const [isSearching, setIsSearching] = useState(false);
  const [showSuggestions, setShowSuggestions] = useState(false);
  const [authModalOpen, setAuthModalOpen] = useState(false);
  const [userMenuOpen, setUserMenuOpen] = useState(false);
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const navigate = useNavigate();
  const location = useLocation();
  const searchRef = useRef<HTMLDivElement>(null);
  const userMenuRef = useRef<HTMLDivElement>(null);
  const { user, signOut } = useAuth();

  // Close mobile menu on route change
  useEffect(() => {
    setMobileMenuOpen(false);
  }, [location.pathname]);

  useEffect(() => {
    const handleScroll = () => {
      const currentY = window.scrollY;
      setIsScrolled(currentY > 10);
      if (currentY > 80) {
        setIsHidden(currentY > lastScrollY.current);
      } else {
        setIsHidden(false);
      }
      lastScrollY.current = currentY;
    };
    window.addEventListener('scroll', handleScroll, { passive: true });
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (searchRef.current && !searchRef.current.contains(event.target as Node)) {
        setShowSuggestions(false);
      }
      if (userMenuRef.current && !userMenuRef.current.contains(event.target as Node)) {
        setUserMenuOpen(false);
      }
    };
    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, []);

  const handleSignOut = async () => {
    await signOut();
    setUserMenuOpen(false);
  };

  useEffect(() => {
    const timer = setTimeout(async () => {
      if (searchQuery.length >= 2) {
        setIsSearching(true);
        try {
          const response = await animeAPI.search(searchQuery);
          const animes: any[] = response.data?.data || [];
          const normalized = animes.map((anime: any) => {
            const poster = anime.images?.jpg?.large_image_url ||
              anime.images?.jpg?.image_url ||
              anime.image_url ||
              '';
            return {
              ...anime,
              id: anime.mal_id?.toString() || anime.id?.toString(),
              title: anime.title || anime.name || 'Unknown Title',
              poster: poster,
            };
          });
          setSuggestions(normalized.slice(0, 6));
          setShowSuggestions(true);
        } catch (error) {
          console.error('Search suggestions failed', error);
        } finally {
          setIsSearching(false);
        }
      } else {
        setSuggestions([]);
        setShowSuggestions(false);
      }
    }, 300);

    return () => clearTimeout(timer);
  }, [searchQuery]);

  const handleSearch = (e: React.FormEvent) => {
    e.preventDefault();
    if (searchQuery.trim()) {
      navigate(`/search?q=${encodeURIComponent(searchQuery)}`);
      setShowSuggestions(false);
      setSearchOpen(false);
    }
  };

  const selectSuggestion = (anime: any) => {
    navigate(`/anime/${anime.id}`);
    setSearchQuery('');
    setSearchOpen(false);
    setShowSuggestions(false);
  };

  const navLinks = [
    { to: '/', label: 'Home', icon: Home },
    { to: '/latest', label: 'Latest', icon: Clock },
    { to: '/tv-series', label: 'TV Shows', icon: Tv },
    { to: '/movies', label: 'Movies', icon: Film },
    { to: '/schedule', label: 'Schedule', icon: Calendar },
    { to: '/favorites', label: 'Favorites', icon: Heart },
    { to: '/history', label: 'History', icon: HistoryIcon },
  ];

  return (
    <>
      <nav className={`navbar ${isScrolled ? 'scrolled' : ''}`} style={{
        position: 'fixed', top: 0, width: '100%', height: 'clamp(56px, 8vh, 68px)', padding: '0 clamp(1rem, 4vw, 4%)',
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
        transition: 'background 0.3s ease, transform 0.35s cubic-bezier(0.4, 0, 0.2, 1)',
        transform: isHidden ? 'translateY(-100%)' : 'translateY(0)',
        backgroundColor: isScrolled ? 'var(--net-bg)' : 'transparent',
        backgroundImage: isScrolled ? 'none' : 'var(--net-gradient)',
        zIndex: 1000,
        maxWidth: '100vw'
      }}>
        {/* Left: Logo + Desktop Nav */}
        <div style={{ display: 'flex', alignItems: 'center', gap: 'clamp(1rem, 3vw, 2.5rem)', minWidth: 0 }}>
          <Link to="/" style={{ color: 'var(--net-red)', fontSize: 'clamp(1.2rem, 4vw, 1.8rem)', fontWeight: 800, letterSpacing: '-1px', display: 'flex', alignItems: 'center', gap: '4px', whiteSpace: 'nowrap', flexShrink: 0 }}>
            ANIME<span style={{ color: 'white' }}>PRO</span>
          </Link>
          {/* Desktop Nav Links */}
          <div className="desktop-nav" style={{ gap: 'clamp(0.75rem, 2vw, 1.5rem)', fontSize: 'clamp(0.8rem, 2vw, 0.92rem)', fontWeight: 500 }}>
            {navLinks.map(link => (
              <Link
                key={link.to}
                to={link.to}
                className="nav-link"
                style={{
                  display: 'flex', alignItems: 'center', gap: '4px',
                  color: location.pathname === link.to ? 'white' : 'var(--net-text-muted)',
                  fontWeight: location.pathname === link.to ? 700 : 500,
                }}
              >
                {(link.to === '/favorites' || link.to === '/history') && (
                  <link.icon size={14} fill={link.to === '/favorites' ? 'var(--net-red)' : 'none'} style={{ color: 'var(--net-red)' }} />
                )}
                {link.label}
              </Link>
            ))}
          </div>
        </div>

        {/* Right: Search + User + Mobile Menu Toggle */}
        <div style={{ display: 'flex', alignItems: 'center', gap: 'clamp(0.5rem, 2vw, 1rem)', flexShrink: 0 }}>
          {/* Search */}
          <div ref={searchRef} style={{ position: 'relative' }}>
            <form onSubmit={handleSearch} style={{
              display: 'flex', alignItems: 'center',
              background: searchOpen ? 'rgba(0,0,0,0.85)' : 'transparent',
              border: searchOpen ? '1px solid rgba(255,255,255,0.4)' : 'none',
              padding: searchOpen ? '6px 12px' : '0',
              borderRadius: '4px', transition: 'all 0.4s cubic-bezier(0.19, 1, 0.22, 1)',
              width: searchOpen ? 'clamp(160px, 28vw, 260px)' : '32px'
            }}>
              <button type="button" onClick={() => setSearchOpen(!searchOpen)} style={{ color: 'white', display: 'flex', alignItems: 'center', flexShrink: 0 }}>
                <Search size={20} />
              </button>
              <AnimatePresence>
                {searchOpen && (
                  <motion.input initial={{ width: 0, opacity: 0 }} animate={{ width: '100%', opacity: 1 }} exit={{ width: 0, opacity: 0 }}
                    type="text" placeholder="Search anime..."
                    value={searchQuery} onChange={e => setSearchQuery(e.target.value)}
                    style={{ background: 'transparent', border: 'none', color: 'white', outline: 'none', marginLeft: '12px', fontSize: '0.9rem', width: '100%' }}
                    autoFocus />
                )}
              </AnimatePresence>
              {searchQuery && searchOpen && (
                <button onClick={() => setSearchQuery('')} type="button" style={{ color: 'var(--net-text-muted)', flexShrink: 0 }}>
                  {isSearching ? <Loader2 size={16} className="animate-spin" /> : <X size={16} />}
                </button>
              )}
            </form>

            {/* Suggestions dropdown */}
            <AnimatePresence>
              {showSuggestions && suggestions.length > 0 && (
                <motion.div initial={{ opacity: 0, y: 10, scale: 0.95 }} animate={{ opacity: 1, y: 0, scale: 1 }} exit={{ opacity: 0, y: 10, scale: 0.95 }}
                  className="glass"
                  style={{ zIndex: 1001, position: 'absolute', top: '100%', right: 0, marginTop: '12px', width: 'clamp(280px, 40vw, 360px)', borderRadius: '12px', overflow: 'hidden', boxShadow: '0 20px 40px rgba(0,0,0,0.6)', padding: '8px' }}>
                  {suggestions.map(anime => (
                    <div key={anime.id} onClick={() => selectSuggestion(anime)}
                      style={{ display: 'flex', gap: '12px', padding: '10px', cursor: 'pointer', borderRadius: '8px', transition: 'var(--transition)' }}
                      className="suggestion-item"
                      onMouseEnter={(e: React.MouseEvent<HTMLDivElement>) => (e.currentTarget.style.background = 'rgba(255,255,255,0.1)')}
                      onMouseLeave={(e: React.MouseEvent<HTMLDivElement>) => (e.currentTarget.style.background = 'transparent')}>
                      <img src={anime.poster} alt={anime.title}
                        style={{ width: '40px', height: '56px', borderRadius: '4px', objectFit: 'cover', flexShrink: 0 }} />
                      <div style={{ display: 'flex', flexDirection: 'column', gap: '4px', overflow: 'hidden', justifyContent: 'center' }}>
                        <span className="line-clamp-1" style={{ fontWeight: 600, fontSize: '0.9rem', color: 'white' }}>
                          {anime.title}
                        </span>
                      </div>
                    </div>
                  ))}
                </motion.div>
              )}
            </AnimatePresence>
          </div>

          {/* Bell (desktop only) */}
          <Bell size={20} className="desktop-only-icon" style={{ color: 'white', cursor: 'pointer' }} />

          {/* User Section */}
          {user ? (
            <div ref={userMenuRef} style={{ position: 'relative' }}>
              <button
                onClick={() => setUserMenuOpen(!userMenuOpen)}
                style={{
                  display: 'flex', alignItems: 'center', gap: '0.5rem',
                  padding: '0.4rem', borderRadius: '8px',
                  backgroundColor: 'rgba(255, 255, 255, 0.1)', border: 'none', cursor: 'pointer', transition: 'all 0.2s',
                }}
                onMouseEnter={(e) => { e.currentTarget.style.backgroundColor = 'rgba(255, 255, 255, 0.15)'; }}
                onMouseLeave={(e) => { e.currentTarget.style.backgroundColor = 'rgba(255, 255, 255, 0.1)'; }}
              >
                <div style={{ width: '30px', height: '30px', borderRadius: '50%', backgroundColor: 'var(--net-red)', display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'white', fontWeight: 600, fontSize: '0.875rem' }}>
                  {user.email?.[0].toUpperCase()}
                </div>
                <ChevronDown size={14} style={{ color: 'white' }} className="desktop-only-icon" />
              </button>

              <AnimatePresence>
                {userMenuOpen && (
                  <motion.div
                    initial={{ opacity: 0, y: 10, scale: 0.95 }}
                    animate={{ opacity: 1, y: 0, scale: 1 }}
                    exit={{ opacity: 0, y: 10, scale: 0.95 }}
                    className="glass"
                    style={{ zIndex: 1001, position: 'absolute', top: '100%', right: 0, marginTop: '12px', width: '200px', borderRadius: '12px', overflow: 'hidden', boxShadow: '0 20px 40px rgba(0,0,0,0.6)', padding: '8px' }}
                  >
                    <div style={{ padding: '12px', borderBottom: '1px solid rgba(255, 255, 255, 0.1)', marginBottom: '8px' }}>
                      <p style={{ color: 'white', fontWeight: 600, fontSize: '0.9rem', marginBottom: '2px' }}>
                        {user.user_metadata?.username || user.email?.split('@')[0]}
                      </p>
                      <p style={{ color: 'var(--net-text-muted)', fontSize: '0.8rem' }}>{user.email}</p>
                    </div>
                    <Link to="/favorites" onClick={() => setUserMenuOpen(false)} style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', padding: '0.75rem 1rem', color: 'var(--net-text-muted)', borderRadius: '8px', fontSize: '0.9rem' }}
                      onMouseEnter={(e: any) => { e.currentTarget.style.backgroundColor = 'rgba(255,255,255,0.1)'; e.currentTarget.style.color = 'white'; }}
                      onMouseLeave={(e: any) => { e.currentTarget.style.backgroundColor = 'transparent'; e.currentTarget.style.color = 'var(--net-text-muted)'; }}>
                      <Heart size={16} /> Favorites
                    </Link>
                    <Link to="/history" onClick={() => setUserMenuOpen(false)} style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', padding: '0.75rem 1rem', color: 'var(--net-text-muted)', borderRadius: '8px', fontSize: '0.9rem' }}
                      onMouseEnter={(e: any) => { e.currentTarget.style.backgroundColor = 'rgba(255,255,255,0.1)'; e.currentTarget.style.color = 'white'; }}
                      onMouseLeave={(e: any) => { e.currentTarget.style.backgroundColor = 'transparent'; e.currentTarget.style.color = 'var(--net-text-muted)'; }}>
                      <HistoryIcon size={16} /> History
                    </Link>
                    <button
                      onClick={handleSignOut}
                      style={{ width: '100%', display: 'flex', alignItems: 'center', gap: '0.75rem', padding: '0.75rem 1rem', backgroundColor: 'transparent', border: 'none', color: 'var(--net-text-muted)', cursor: 'pointer', borderRadius: '8px', fontSize: '0.9rem', fontWeight: 500, transition: 'all 0.2s' }}
                      onMouseEnter={(e) => { e.currentTarget.style.backgroundColor = 'rgba(255, 255, 255, 0.1)'; e.currentTarget.style.color = 'white'; }}
                      onMouseLeave={(e) => { e.currentTarget.style.backgroundColor = 'transparent'; e.currentTarget.style.color = 'var(--net-text-muted)'; }}
                    >
                      <LogOut size={16} /> Sign Out
                    </button>
                  </motion.div>
                )}
              </AnimatePresence>
            </div>
          ) : (
            <button
              onClick={() => setAuthModalOpen(true)}
              className="sign-in-btn"
              style={{ display: 'flex', alignItems: 'center', gap: '0.4rem', padding: '0.5rem 1rem', borderRadius: '8px', backgroundColor: 'var(--net-red)', border: 'none', color: 'white', fontWeight: 600, fontSize: 'clamp(0.75rem, 2vw, 0.9rem)', cursor: 'pointer', transition: 'all 0.2s', whiteSpace: 'nowrap' }}
              onMouseEnter={(e: React.MouseEvent<HTMLButtonElement>) => { e.currentTarget.style.backgroundColor = 'var(--net-red-hover)'; e.currentTarget.style.transform = 'translateY(-2px)'; }}
              onMouseLeave={(e: React.MouseEvent<HTMLButtonElement>) => { e.currentTarget.style.backgroundColor = 'var(--net-red)'; e.currentTarget.style.transform = 'translateY(0)'; }}
            >
              <User size={16} /><span className="sign-in-text">Sign In</span>
            </button>
          )}

          {/* Hamburger Menu (Mobile only) */}
          <button
            className="hamburger-btn"
            onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
            style={{ color: 'white', display: 'none', alignItems: 'center', justifyContent: 'center', padding: '6px', borderRadius: '8px', backgroundColor: 'rgba(255,255,255,0.08)', border: 'none', cursor: 'pointer' }}
            aria-label="Open menu"
          >
            {mobileMenuOpen ? <X size={22} /> : <Menu size={22} />}
          </button>
        </div>
      </nav>

      {/* Mobile Drawer */}
      <AnimatePresence>
        {mobileMenuOpen && (
          <>
            {/* Backdrop */}
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              onClick={() => setMobileMenuOpen(false)}
              style={{ position: 'fixed', inset: 0, backgroundColor: 'rgba(0,0,0,0.7)', zIndex: 998, backdropFilter: 'blur(4px)' }}
            />
            {/* Drawer */}
            <motion.div
              initial={{ x: '-100%' }}
              animate={{ x: 0 }}
              exit={{ x: '-100%' }}
              transition={{ type: 'spring', damping: 28, stiffness: 300 }}
              style={{ position: 'fixed', top: 0, left: 0, bottom: 0, width: 'min(82vw, 300px)', backgroundColor: '#111', zIndex: 999, padding: '0', overflowY: 'auto', boxShadow: '4px 0 40px rgba(0,0,0,0.6)' }}
            >
              {/* Drawer Header */}
              <div style={{ padding: '1.25rem 1.25rem 1rem', borderBottom: '1px solid rgba(255,255,255,0.08)', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                <Link to="/" style={{ color: 'var(--net-red)', fontSize: '1.5rem', fontWeight: 800, letterSpacing: '-1px' }} onClick={() => setMobileMenuOpen(false)}>
                  ANIME<span style={{ color: 'white' }}>PRO</span>
                </Link>
                <button onClick={() => setMobileMenuOpen(false)} style={{ color: 'var(--net-text-muted)', background: 'rgba(255,255,255,0.08)', border: 'none', borderRadius: '8px', padding: '6px', display: 'flex', cursor: 'pointer' }}>
                  <X size={20} />
                </button>
              </div>

              {/* User info if signed in */}
              {user && (
                <div style={{ padding: '1rem 1.25rem', borderBottom: '1px solid rgba(255,255,255,0.05)', display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
                  <div style={{ width: '38px', height: '38px', borderRadius: '50%', backgroundColor: 'var(--net-red)', display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'white', fontWeight: 700, fontSize: '1rem', flexShrink: 0 }}>
                    {user.email?.[0].toUpperCase()}
                  </div>
                  <div style={{ minWidth: 0 }}>
                    <p style={{ color: 'white', fontWeight: 600, fontSize: '0.9rem', margin: 0, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{user.user_metadata?.username || user.email?.split('@')[0]}</p>
                    <p style={{ color: 'var(--net-text-muted)', fontSize: '0.75rem', margin: 0, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{user.email}</p>
                  </div>
                </div>
              )}

              {/* Nav Links */}
              <nav style={{ padding: '0.75rem 0' }}>
                {navLinks.map((link) => (
                  <Link
                    key={link.to}
                    to={link.to}
                    onClick={() => setMobileMenuOpen(false)}
                    style={{
                      display: 'flex', alignItems: 'center', gap: '0.85rem',
                      padding: '0.85rem 1.25rem',
                      color: location.pathname === link.to ? 'white' : 'var(--net-text-muted)',
                      backgroundColor: location.pathname === link.to ? 'rgba(229,9,20,0.12)' : 'transparent',
                      fontWeight: location.pathname === link.to ? 600 : 400,
                      fontSize: '1rem',
                      borderLeft: location.pathname === link.to ? '3px solid var(--net-red)' : '3px solid transparent',
                      transition: 'all 0.2s',
                    }}
                  >
                    <link.icon size={18} style={{ color: location.pathname === link.to ? 'var(--net-red)' : 'var(--net-text-muted)', flexShrink: 0 }} />
                    {link.label}
                  </Link>
                ))}
              </nav>

              {/* Bottom actions */}
              <div style={{ padding: '0.75rem 1.25rem 1.5rem', borderTop: '1px solid rgba(255,255,255,0.05)', marginTop: 'auto' }}>
                {user ? (
                  <button
                    onClick={() => { handleSignOut(); setMobileMenuOpen(false); }}
                    style={{ width: '100%', display: 'flex', alignItems: 'center', gap: '0.75rem', padding: '0.85rem 1rem', backgroundColor: 'rgba(229,9,20,0.1)', border: '1px solid rgba(229,9,20,0.25)', color: '#f87171', cursor: 'pointer', borderRadius: '10px', fontSize: '0.95rem', fontWeight: 500 }}
                  >
                    <LogOut size={18} /> Sign Out
                  </button>
                ) : (
                  <button
                    onClick={() => { setAuthModalOpen(true); setMobileMenuOpen(false); }}
                    style={{ width: '100%', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.75rem', padding: '0.85rem 1rem', backgroundColor: 'var(--net-red)', border: 'none', color: 'white', cursor: 'pointer', borderRadius: '10px', fontSize: '0.95rem', fontWeight: 700 }}
                  >
                    <User size={18} /> Sign In
                  </button>
                )}
              </div>
            </motion.div>
          </>
        )}
      </AnimatePresence>

      {/* CSS for responsive navbar */}
      <style>{`
        .desktop-nav {
          display: flex;
          align-items: center;
        }
        .desktop-only-icon {
          display: block;
        }
        .hamburger-btn {
          display: none !important;
        }
        @media (max-width: 768px) {
          .desktop-nav {
            display: none !important;
          }
          .desktop-only-icon {
            display: none !important;
          }
          .hamburger-btn {
            display: flex !important;
          }
          .sign-in-text {
            display: none;
          }
          .sign-in-btn {
            padding: 0.5rem !important;
            border-radius: 50% !important;
          }
        }
      `}</style>

      {/* Auth Modal */}
      <AuthModal isOpen={authModalOpen} onClose={() => setAuthModalOpen(false)} />
    </>
  );
};

export default Navbar;

// sveltekit-frontend/src/lib/components/Navbar.svelte
<script lang="ts">
  import { api, getProxiedImage } from "$lib/api";
  import { Download, Heart } from 'lucide-svelte';
  import { auth, logoutUser } from "$lib/stores/auth";
  import { goto } from "$app/navigation";
  import { page } from "$app/state";
  import { onMount } from "svelte";

  let scrolled = $state(false);
  let searchOpen = $state(false);
  let searchQuery = $state("");
  let suggestions = $state<any[]>([]);

  let isSearching = $state(false);
  let showSuggestions = $state(false);
  let mobileMenuOpen = $state(false);
  let profileOpen = $state(false);
  let searchContainer: HTMLElement = $state(null!);
  let profileContainer: HTMLElement = $state(null!);

  const navLinks = [
    { href: "/", label: "Home" },
    { href: "/latest", label: "Latest" },
    { href: "/schedule", label: "Schedule" },
    { href: "/tv-series", label: "TV Series" },
    { href: "/movies", label: "Movies" },
    { href: "/intel", label: "Intel Center" },
  ];

  function handleScroll() {
    scrolled = window.scrollY > 50;
  }

  function handleSearch(e: KeyboardEvent) {
    if (e.key === "Enter") {
      executeSearch();
    }
  }

  function executeSearch() {
    if (!searchQuery.trim()) return;
    goto(`/search?q=${encodeURIComponent(searchQuery.trim())}`);
    searchOpen = false;
    showSuggestions = false;
  }

  async function handleRandom() {
    try {
      const id = await api.getRandomAnime();
      if (id) goto(`/anime/${id}`);
    } catch {}
  }

  function selectSuggestion(anime: any) {
    goto(`/anime/${anime.id}`);
    searchQuery = "";
    searchOpen = false;
    showSuggestions = false;
  }

  // Svelte 5 Debounced Search Effect
  $effect(() => {
    if (searchQuery.trim().length < 2) {
      suggestions = [];
      showSuggestions = false;
      return;
    }

    const timer = setTimeout(async () => {
      isSearching = true;
      try {
        const res = await api.search(searchQuery);
        suggestions = res.data.slice(0, 6);
        showSuggestions = true;
      } catch (err) {
        console.error("Search error:", err);
        suggestions = [];
      } finally {
        isSearching = false;
      }
    }, 300);

    return () => clearTimeout(timer);
  });

  onMount(() => {
    const handleClick = (e: MouseEvent) => {
      if (searchContainer && !searchContainer.contains(e.target as Node)) {
        showSuggestions = false;
      }
      if (profileContainer && !profileContainer.contains(e.target as Node)) {
        profileOpen = false;
      }
    };
    window.addEventListener("click", handleClick);
    return () => window.removeEventListener("click", handleClick);
  });
</script>

<svelte:window onscroll={handleScroll} />

<nav class="navbar" class:scrolled>
  <div class="nav-inner">
    <a href="/" class="logo">
      <span class="logo-text">ANIME<span class="logo-accent">PRO</span></span>
    </a>

    <div class="nav-links hide-mobile">
      {#each navLinks as link}
        <a
          href={link.href}
          class="nav-link"
          class:active={page.url.pathname === link.href}>{link.label}</a
        >
      {/each}
    </div>

    <div class="nav-actions">
      <button class="nav-icon-btn hide-mobile" onclick={handleRandom} title="Random Anime"
        >🎲</button
      >

      <a href="/download" class="nav-icon-btn hide-mobile" title="Download Apps">
        <Download size={20} />
      </a>

      <a href="/donate" class="nav-icon-btn text-pink-500 hide-mobile" title="Donate">
        <Heart size={20} fill="currentColor" />
      </a>

      <div class="search-container" bind:this={searchContainer}>
        {#if searchOpen}
          <div class="search-box glass">
            <input
              type="text"
              placeholder="Search anime..."
              bind:value={searchQuery}
              onkeydown={handleSearch}
              onfocus={() => suggestions.length > 0 && (showSuggestions = true)}
            />
            {#if isSearching}
              <div class="search-spinner"></div>
            {/if}
            <button
              class="close-btn"
              onclick={() => {
                searchOpen = false;
                searchQuery = "";
                showSuggestions = false;
              }}>✕</button
            >
          </div>
        {:else}
          <button class="nav-icon-btn" onclick={() => (searchOpen = true)}
            >🔍</button
          >
        {/if}

        {#if showSuggestions && (suggestions.length > 0 || isSearching)}
          <div class="suggestions-dropdown glass">
            {#if isSearching && suggestions.length === 0}
              <div class="searching-state">Searching...</div>
            {:else}
              {#each suggestions as anime}
                <button
                  class="suggestion-item"
                  onclick={() => selectSuggestion(anime)}
                >
                  <img
                    src={getProxiedImage(anime.poster)}
                    alt={anime.title}
                    class="suggestion-poster"
                  />
                  <div class="suggestion-info">
                    <span class="suggestion-title">{anime.title}</span>
                    <div class="suggestion-meta">
                      <span class="suggestion-type">{anime.type}</span>
                      <span class="suggestion-score"
                        >⭐ {anime.score || "N/A"}</span
                      >
                    </div>
                  </div>
                </button>
              {/each}
            {/if}
          </div>
        {/if}
      </div>

      <button
        class="nav-icon-btn hamburger hide-desktop"
        onclick={() => (mobileMenuOpen = !mobileMenuOpen)}>☰</button
      >

      {#if $auth.user}
        <div class="user-profile" class:open={profileOpen} bind:this={profileContainer}>
          <button class="profile-trigger" title="Account" onclick={(e) => { e.stopPropagation(); profileOpen = !profileOpen; }}>
            <img
              src={getProxiedImage(
                ($auth.currentProfile?.avatar) ||
                  `https://api.dicebear.com/7.x/avataaars/svg?seed=${$auth.user?.email || 'guest'}`,
              )}
              alt="Profile"
            />
          </button>

          <div class="profile-dropdown glass">
            <div class="user-info">
              <span class="user-name"
                >{$auth.currentProfile?.name || "User"}</span
              >
              <span class="user-email">{$auth.user.email}</span>
            </div>
            <hr />
            <a href="/profile" class="dropdown-item" onclick={() => profileOpen = false}>My Profile</a>
            <a href="/watchlist" class="dropdown-item" onclick={() => profileOpen = false}>Watchlist</a>
            <a href="/favorites" class="dropdown-item" onclick={() => profileOpen = false}>Favorites</a>
            <button
              class="dropdown-item logout"
              onclick={() => {
                profileOpen = false;
                logoutUser();
                goto("/");
              }}>Logout</button
            >
          </div>
        </div>
      {:else}
        <!-- Give unauthenticated users a guest profile dropdown instead of raw buttons on home screen -->
        <div class="user-profile hide-mobile">
          <button class="profile-trigger" title="Guest">
            <img
              src="https://api.dicebear.com/7.x/avataaars/svg?seed=guest&backgroundColor=b6e3f4"
              alt="Guest"
            />
          </button>
          <div class="profile-dropdown glass">
            <div class="user-info">
              <span class="user-name">Guest User</span>
              <span class="user-email">Not logged in</span>
            </div>
            <hr />
            <a href="/auth/login" class="dropdown-item">Login</a>
            <a href="/auth/register" class="dropdown-item accent">Sign Up</a>
          </div>
        </div>
      {/if}
    </div>
  </div>

  {#if mobileMenuOpen}
    <div class="mobile-menu glass">
      {#each navLinks as link}
        <a
          href={link.href}
          class="mobile-link"
          onclick={() => (mobileMenuOpen = false)}>{link.label}</a
        >
      {/each}
      {#if !$auth.user}
        <hr />
        <a
          href="/auth/login"
          class="mobile-link"
          onclick={() => (mobileMenuOpen = false)}>Login</a
        >
        <a
          href="/auth/register"
          class="mobile-link accent"
          onclick={() => (mobileMenuOpen = false)}>Sign Up</a
        >
      {/if}
    </div>
  {/if}
</nav>

<style>
  .navbar {
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    z-index: 1000;
    padding: 0.75rem 1rem;
    padding-top: max(0.75rem, env(safe-area-inset-top));
    padding-left: max(1rem, env(safe-area-inset-left));
    padding-right: max(1rem, env(safe-area-inset-right));
    background: linear-gradient(
      180deg,
      rgba(0, 0, 0, 0.8) 0%,
      transparent 100%
    );
    transition: background 0.3s ease;
  }
  .navbar.scrolled {
    background: var(--net-bg);
    box-shadow: 0 4px 20px rgba(0, 0, 0, 0.3);
  }
  .nav-inner {
    display: flex;
    align-items: center;
    justify-content: space-between;
    max-width: 1400px;
    margin: 0 auto;
  }

  .logo {
    font-size: 1.4rem;
    font-weight: 800;
    letter-spacing: -0.03em;
    text-decoration: none;
    color: white;
  }
  .logo-accent {
    color: var(--net-red);
  }

  .nav-links {
    display: flex;
    gap: 1.5rem;
  }
  .nav-link {
    color: var(--net-text-muted);
    font-weight: 500;
    font-size: 0.95rem;
    transition: color 0.2s;
    text-decoration: none;
    padding: 0.5rem 0;
  }
  .nav-link:hover,
  .nav-link.active {
    color: white;
  }

  .nav-actions {
    display: flex;
    align-items: center;
    gap: 0.5rem;
  }
  .nav-icon-btn {
    color: white;
    font-size: 1.2rem;
    padding: 0.5rem;
    border-radius: 50%;
    transition: var(--transition);
    background: none;
    border: none;
    cursor: pointer;
    min-width: 44px;
    min-height: 44px;
    display: flex;
    align-items: center;
    justify-content: center;
  }
  .nav-icon-btn:hover {
    background: rgba(255, 255, 255, 0.1);
  }

  .search-container {
    position: relative;
    max-width: calc(100vw - env(safe-area-inset-left, 0px) - env(safe-area-inset-right, 0px) - 2rem);
  }
  .search-box {
    display: flex;
    align-items: center;
    background: rgba(40, 40, 40, 0.6);
    border: 1px solid rgba(255, 255, 255, 0.1);
    border-radius: var(--radius-md);
    padding: 0.4rem 0.8rem;
    gap: 0.5rem;
    max-width: 100%;
    box-sizing: border-box;
  }
  .search-box input {
    background: none;
    border: none;
    color: white;
    outline: none;
    font-size: 0.95rem;
    width: 180px;
  }

  .search-spinner {
    width: 14px;
    height: 14px;
    border: 2px solid rgba(255, 255, 255, 0.1);
    border-top-color: var(--net-red);
    border-radius: 50%;
    animation: spin 0.6s linear infinite;
  }
  @keyframes spin {
    to {
      transform: rotate(360deg);
    }
  }

  .close-btn {
    background: none;
    border: none;
    cursor: pointer;
    color: var(--net-text-muted);
    font-size: 0.9rem;
    padding: 4px;
    min-width: 32px;
    min-height: 32px;
  }

  .suggestions-dropdown {
    position: absolute;
    top: 115%;
    right: 0;
    width: 300px;
    background: rgba(20, 20, 20, 0.95);
    backdrop-filter: blur(20px);
    border: 1px solid rgba(255, 255, 255, 0.1);
    border-top: 1px solid var(--net-red);
    border-radius: var(--radius-lg);
    box-shadow: 0 20px 50px rgba(0, 0, 0, 0.8);
    overflow: hidden;
    padding: 0.5rem;
    z-index: 1001;
  }

  .searching-state {
    padding: 1rem;
    text-align: center;
    color: var(--net-text-muted);
    font-size: 0.9rem;
  }

  .suggestion-item {
    display: flex;
    gap: 0.75rem;
    width: 100%;
    padding: 0.6rem;
    background: none;
    border: none;
    border-radius: var(--radius-md);
    cursor: pointer;
    text-align: left;
    transition: background 0.2s;
    min-height: 44px;
  }
  .suggestion-item:hover {
    background: rgba(255, 255, 255, 0.1);
  }

  .suggestion-poster {
    width: 40px;
    height: 56px;
    border-radius: 4px;
    object-fit: cover;
    background: #222;
    flex-shrink: 0;
  }
  .suggestion-info {
    display: flex;
    flex-direction: column;
    gap: 0.2rem;
    overflow: hidden;
    min-width: 0;
  }
  .suggestion-title {
    color: white;
    font-weight: 600;
    font-size: 0.9rem;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
  }
  .suggestion-meta {
    display: flex;
    gap: 0.5rem;
    font-size: 0.75rem;
    color: var(--net-text-muted);
  }
  .suggestion-score {
    color: #fbbf24;
  }

  .mobile-menu {
    display: flex;
    flex-direction: column;
    padding: 1rem;
    gap: 0.5rem;
    position: absolute;
    top: 100%;
    left: 0;
    right: 0;
    background: var(--net-bg);
    border-top: 1px solid rgba(255, 255, 255, 0.1);
    max-height: calc(100vh - 64px);
    overflow-y: auto;
    animation: slideDown 0.3s ease;
  }
  @keyframes slideDown {
    from {
      opacity: 0;
      transform: translateY(-10px);
    }
    to {
      opacity: 1;
      transform: translateY(0);
    }
  }
  .mobile-link {
    color: var(--net-text-muted);
    font-weight: 500;
    padding: 0.75rem 1rem;
    text-decoration: none;
    border-radius: var(--radius-md);
    transition: background 0.2s;
    min-height: 44px;
    display: flex;
    align-items: center;
  }
  .mobile-link:hover {
    background: rgba(255, 255, 255, 0.05);
    color: white;
  }
  .mobile-link.accent {
    color: var(--net-red);
    font-weight: 700;
  }

  .hide-mobile {
    display: none;
  }
  .hide-desktop {
    display: block;
  }
  @media (min-width: 768px) {
    .hide-mobile {
      display: flex;
    }
    .hide-desktop {
      display: none;
    }
    .navbar {
      padding: 0.75rem 2rem;
    }
    .logo {
      font-size: 1.6rem;
    }
    .search-box input {
      width: 220px;
    }
    .suggestions-dropdown {
      width: 320px;
    }
    .suggestion-poster {
      width: 44px;
      height: 62px;
    }
    .mobile-menu {
      padding: 1rem 2rem;
    }
  }
  .hamburger {
    font-size: 1.5rem;
  }


  .user-profile {
    position: relative;
    margin-left: 0.5rem;
  }
  .profile-trigger {
    width: 36px;
    height: 36px;
    border-radius: 8px;
    overflow: hidden;
    border: 2px solid rgba(255, 255, 255, 0.1);
    cursor: pointer;
    padding: 0;
    transition: border-color 0.2s;
    min-width: 36px;
    min-height: 36px;
  }
  .profile-trigger:hover {
    border-color: var(--net-red);
  }
  .profile-trigger img {
    width: 100%;
    height: 100%;
    object-fit: cover;
  }

  .profile-dropdown {
    position: absolute;
    top: 120%;
    right: 0;
    width: 220px;
    max-width: calc(100vw - 2rem);
    border-radius: 12px;
    box-shadow: 0 10px 40px rgba(0, 0, 0, 0.5);
    opacity: 0;
    visibility: hidden;
    transform: translateY(-10px);
    transition: 0.2s cubic-bezier(0.165, 0.84, 0.44, 1);
    padding: 0.75rem;
    border: 1px solid rgba(255, 255, 255, 0.1);
  }
  /* Desktop only: hover to open */
  @media (hover: hover) {
    .user-profile:hover .profile-dropdown {
      opacity: 1;
      visibility: visible;
      transform: translateY(0);
    }
  }
  /* Both desktop and mobile: click/tap to open */
  .user-profile.open .profile-dropdown {
    opacity: 1;
    visibility: visible;
    transform: translateY(0);
  }

  .user-info {
    display: flex;
    flex-direction: column;
    padding: 0.5rem;
  }
  .user-name {
    font-weight: 700;
    color: white;
    font-size: 0.95rem;
  }
  .user-email {
    font-size: 0.75rem;
    color: var(--net-text-muted);
  }

  hr {
    border: none;
    border-top: 1px solid rgba(255, 255, 255, 0.1);
    margin: 0.5rem 0;
  }
  .dropdown-item {
    display: block;
    width: 100%;
    text-align: left;
    padding: 0.6rem 0.8rem;
    border-radius: 8px;
    font-size: 0.9rem;
    color: var(--net-text-muted);
    text-decoration: none;
    background: none;
    border: none;
    cursor: pointer;
    transition: 0.2s;
    min-height: 40px;
  }
  .dropdown-item:hover {
    background: rgba(255, 255, 255, 0.05);
    color: white;
  }
  .dropdown-item.logout {
    color: #f87171;
  }
  .dropdown-item.logout:hover {
    background: rgba(248, 113, 113, 0.1);
  }

  /* Mobile-specific improvements */
  @media (max-width: 480px) {
    .navbar {
      padding: 0.6rem 0.75rem;
      padding-top: max(0.6rem, env(safe-area-inset-top));
      padding-left: max(0.75rem, env(safe-area-inset-left));
      padding-right: max(0.75rem, env(safe-area-inset-right));
    }
    .logo {
      font-size: 1.2rem;
    }
    .nav-icon-btn {
      font-size: 1.1rem;
      padding: 0.4rem;
    }
    .search-box {
      max-width: calc(100vw - env(safe-area-inset-left, 0px) - env(safe-area-inset-right, 0px) - 4rem);
    }
    .search-box input {
      width: 120px;
      min-width: 0;
      flex: 1;
      font-size: 0.9rem;
    }
    .suggestions-dropdown {
      position: fixed;
      top: calc(60px + env(safe-area-inset-top, 0px));
      left: max(10px, env(safe-area-inset-left, 10px));
      right: max(10px, env(safe-area-inset-right, 10px));
      width: auto !important;
      transform: none !important;
      border-radius: 12px;
      z-index: 2000;
      max-height: 70vh;
      overflow-y: auto;
    }
    .suggestion-poster {
      width: 36px;
      height: 50px;
    }
    .profile-dropdown {
      width: 200px;
      right: -0.5rem;
    }
    .mobile-menu {
      padding: 0.75rem;
      padding-left: max(0.75rem, env(safe-area-inset-left));
      padding-right: max(0.75rem, env(safe-area-inset-right));
      max-height: calc(100vh - 56px);
    }
    .mobile-link {
      padding: 0.6rem 0.75rem;
      font-size: 0.95rem;
    }
  }

  @media (max-width: 360px) {
    .navbar {
      padding: 0.5rem 0.5rem;
      padding-top: max(0.5rem, env(safe-area-inset-top));
      padding-left: max(0.5rem, env(safe-area-inset-left));
      padding-right: max(0.5rem, env(safe-area-inset-right));
    }
    .logo {
      font-size: 1.1rem;
    }
    .nav-icon-btn {
      font-size: 1rem;
      padding: 0.35rem;
      min-width: 40px;
      min-height: 40px;
    }
    .search-box {
      max-width: calc(100vw - env(safe-area-inset-left, 0px) - env(safe-area-inset-right, 0px) - 3rem);
    }
    .search-box input {
      width: 100px;
      min-width: 0;
      flex: 1;
      font-size: 0.85rem;
    }
    .suggestions-dropdown {
      left: max(0.5rem, env(safe-area-inset-left, 0.5rem));
      right: max(0.5rem, env(safe-area-inset-right, 0.5rem));
      width: auto;
    }
    .mobile-menu {
      padding: 0.5rem;
      padding-left: max(0.5rem, env(safe-area-inset-left));
      padding-right: max(0.5rem, env(safe-area-inset-right));
    }
    .mobile-link {
      padding: 0.5rem;
      font-size: 0.9rem;
    }
  }
</style>
