// jikan-frontend/src/components/Row.tsx
import React, { useRef, useState } from 'react';
import { ChevronLeft, ChevronRight } from 'lucide-react';
import AnimeCard from './AnimeCard';
import { motion } from 'framer-motion';

interface RowProps {
  title: string;
  items: any[];
  isLargeRow?: boolean;
}

const Row: React.FC<RowProps> = ({ title, items, isLargeRow }) => {
  const rowRef = useRef<HTMLDivElement>(null);
  const [showLeftArrow, setShowLeftArrow] = useState(false);
  const [showRightArrow, setShowRightArrow] = useState(true);

  const handleScroll = (direction: 'left' | 'right') => {
    if (rowRef.current) {
      const { scrollLeft, clientWidth } = rowRef.current;
      const scrollAmount = clientWidth * 0.8;
      const targetScroll = direction === 'left' ? scrollLeft - scrollAmount : scrollLeft + scrollAmount;

      rowRef.current.scrollTo({
        left: targetScroll,
        behavior: 'smooth'
      });
    }
  };

  const onScroll = () => {
    if (rowRef.current) {
      const { scrollLeft, scrollWidth, clientWidth } = rowRef.current;
      setShowLeftArrow(scrollLeft > 0);
      setShowRightArrow(scrollLeft < scrollWidth - clientWidth - 10);
    }
  };

  if (!items || items.length === 0) return null;

  return (
    <div className="row-container" style={{ marginBottom: '2.5rem', position: 'relative', width: '100%' }}>
      <h2 style={{
        fontSize: 'clamp(1.1rem, 2.5vw, 1.4rem)',
        fontWeight: 700,
        color: 'white',
        marginBottom: '0.75rem',
        paddingLeft: 'clamp(1rem, 4vw, 4%)',
        letterSpacing: '-0.02em',
        lineHeight: 1.2
      }}>
        {title}
      </h2>

      <div style={{ position: 'relative', width: '100%' }} className="group">
        {showLeftArrow && (
          <button
            onClick={() => handleScroll('left')}
            style={{
              position: 'absolute',
              top: 0, bottom: 0, left: 0,
              width: 'clamp(40px, 5vw, 60px)',
              backgroundColor: 'rgba(0,0,0,0.5)',
              zIndex: 20,
              display: 'flex', alignItems: 'center', justifyContent: 'center',
              color: 'white',
              backdropFilter: 'blur(4px)',
              borderTopRightRadius: '4px',
              borderBottomRightRadius: '4px',
              cursor: 'pointer',
              transition: 'background-color 0.3s ease'
            }}
            onMouseEnter={(e) => e.currentTarget.style.backgroundColor = 'rgba(0,0,0,0.7)'}
            onMouseLeave={(e) => e.currentTarget.style.backgroundColor = 'rgba(0,0,0,0.5)'}
          >
            <ChevronLeft size={32} />
          </button>
        )}

        <div
          ref={rowRef}
          onScroll={onScroll}
          style={{
            display: 'flex',
            overflowX: 'auto',
            overflowY: 'hidden',
            gap: 'clamp(8px, 1.5vw, 12px)',
            padding: '10px clamp(1rem, 4vw, 4%)',
            scrollbarWidth: 'none',
            msOverflowStyle: 'none',
            scrollBehavior: 'smooth',
            width: '100%',
            alignItems: 'stretch'
          }}
          className="hide-scrollbar"
        >
          {items.map((item, idx) => (
            <motion.div
              key={`${item.id}-${idx}`}
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ delay: idx * 0.05 }}
              style={{ flexShrink: 0, width: isLargeRow ? 'clamp(140px, 14vw, 180px)' : 'clamp(115px, 12vw, 155px)' }}
            >
              <AnimeCard anime={item} />
            </motion.div>
          ))}
        </div>

        {showRightArrow && (
          <button
            onClick={() => handleScroll('right')}
            style={{
              position: 'absolute',
              top: 0, bottom: 0, right: 0,
              width: 'clamp(40px, 5vw, 60px)',
              backgroundColor: 'rgba(0,0,0,0.5)',
              zIndex: 20,
              display: 'flex', alignItems: 'center', justifyContent: 'center',
              color: 'white',
              backdropFilter: 'blur(4px)',
              borderTopLeftRadius: '4px',
              borderBottomLeftRadius: '4px',
              cursor: 'pointer',
              transition: 'background-color 0.3s ease'
            }}
            onMouseEnter={(e) => e.currentTarget.style.backgroundColor = 'rgba(0,0,0,0.7)'}
            onMouseLeave={(e) => e.currentTarget.style.backgroundColor = 'rgba(0,0,0,0.5)'}
          >
            <ChevronRight size={32} />
          </button>
        )}
      </div>

      <style dangerouslySetInnerHTML={{
        __html: `
        .hide-scrollbar::-webkit-scrollbar {
          display: none;
        }
        .hide-scrollbar {
          -ms-overflow-style: none;
          scrollbar-width: none;
        }
        .row-container .select-none {
          user-select: none;
        }
        @media (max-width: 480px) {
          .row-container {
            margin-bottom: 1.5rem;
          }
        }
      `}} />
    </div>
  );
};

export default Row;

// sveltekit-frontend/src/lib/components/Row.svelte
<script lang="ts">
  import AnimeCard from "./AnimeCard.svelte";

  let {
    title,
    items = [],
    href = "",
  } = $props<{ title: string; items: any[]; href?: string }>();
  let scrollContainer: HTMLDivElement;

  function scrollBy(dir: number) {
    scrollContainer?.scrollBy({ left: dir * 400, behavior: "smooth" });
  }
</script>

{#if items.length > 0}
  <section class="row-section">
    <div class="row-header">
      <h2 class="row-title">{title}</h2>
      {#if href}
        <a {href} class="row-see-all">See All →</a>
      {/if}
    </div>
    <div class="row-wrapper">
      <button class="row-arrow left" onclick={() => scrollBy(-1)}>‹</button>
      <div class="row-scroll" bind:this={scrollContainer}>
        {#each items as anime (anime.id || anime.mal_id)}
          <AnimeCard {anime} />
        {/each}
      </div>
      <button class="row-arrow right" onclick={() => scrollBy(1)}>›</button>
    </div>
  </section>
{/if}

<style>
  .row-section {
    margin-bottom: 2rem;
  }
  .row-header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 0 1rem;
    margin-bottom: 0.75rem;
  }
  .row-title {
    font-size: 1.3rem;
    font-weight: 700;
    letter-spacing: -0.02em;
  }
  .row-see-all {
    color: var(--net-text-muted);
    font-size: 0.85rem;
    transition: color 0.2s;
  }
  .row-see-all:hover {
    color: var(--net-red);
  }
  .row-wrapper {
    position: relative;
  }
  .row-scroll {
    display: flex;
    gap: 0.75rem;
    overflow-x: auto;
    padding: 0.5rem 1rem;
    scroll-snap-type: x mandatory;
    -ms-overflow-style: none;
    scrollbar-width: none;
    -webkit-overflow-scrolling: touch;
  }
  .row-scroll::-webkit-scrollbar {
    display: none;
  }
  .row-arrow {
    position: absolute;
    top: 50%;
    transform: translateY(-50%);
    z-index: 5;
    width: 36px;
    height: 80px;
    border-radius: var(--radius-md);
    background: rgba(20, 20, 20, 0.8);
    color: white;
    font-size: 1.6rem;
    display: flex;
    align-items: center;
    justify-content: center;
    opacity: 0;
    transition: opacity 0.3s;
  }
  .row-wrapper:hover .row-arrow {
    opacity: 1;
  }
  .row-arrow.left {
    left: 0;
  }
  .row-arrow.right {
    right: 0;
  }
  .row-arrow:hover {
    background: rgba(229, 9, 20, 0.8);
  }

  @media (max-width: 768px) {
    .row-section {
      margin-bottom: 1.5rem;
    }
    .row-header {
      padding: 0 0.75rem;
      margin-bottom: 0.5rem;
    }
    .row-title {
      font-size: 1.1rem;
    }
    .row-see-all {
      font-size: 0.8rem;
    }
    .row-scroll {
      gap: 0.5rem;
      padding: 0.5rem 0.75rem;
    }
    .row-arrow {
      display: none;
    }
  }

  @media (max-width: 480px) {
    .row-section {
      margin-bottom: 1.25rem;
    }
    .row-header {
      padding: 0 0.5rem;
      margin-bottom: 0.5rem;
    }
    .row-title {
      font-size: 1rem;
    }
    .row-scroll {
      gap: 0.4rem;
      padding: 0.5rem 0.5rem;
    }
  }
</style>
