// sveltekit-frontend/src/lib/components/Navbar.svelte
<script lang="ts">
  import { api, getProxiedImage } from "$lib/api";
  import { auth, logoutUser } from "$lib/stores/auth";
  import { goto } from "$app/navigation";
  import { page } from "$app/state";
  import { onMount } from "svelte";

  let scrolled = $state(false);
  let searchOpen = $state(false);
  let searchQuery = $state("");
  let suggestions = $state<any[]>([]);

  let isSearching = $state(false);
  let showSuggestions = $state(false);
  let mobileMenuOpen = $state(false);
  let searchContainer: HTMLElement;

  const navLinks = [
    { href: "/", label: "Home" },
    { href: "/latest", label: "Latest" },
    { href: "/schedule", label: "Schedule" },
    { href: "/tv-series", label: "TV Series" },
    { href: "/movies", label: "Movies" },
  ];

  function handleScroll() {
    scrolled = window.scrollY > 50;
  }

  function handleSearch(e: KeyboardEvent) {
    if (e.key === "Enter") {
      executeSearch();
    }
  }

  function executeSearch() {
    if (!searchQuery.trim()) return;
    goto(`/search?q=${encodeURIComponent(searchQuery.trim())}`);
    searchOpen = false;
    showSuggestions = false;
  }

  async function handleRandom() {
    try {
      const id = await api.getRandomAnime();
      if (id) goto(`/anime/${id}`);
    } catch {}
  }

  function selectSuggestion(anime: any) {
    goto(`/anime/${anime.id}`);
    searchQuery = "";
    searchOpen = false;
    showSuggestions = false;
  }

  // Svelte 5 Debounced Search Effect
  $effect(() => {
    if (searchQuery.trim().length < 2) {
      suggestions = [];
      showSuggestions = false;
      return;
    }

    const timer = setTimeout(async () => {
      isSearching = true;
      try {
        const res = await api.search(searchQuery);
        suggestions = res.data.slice(0, 6);
        showSuggestions = true;
      } catch (err) {
        console.error("Search error:", err);
        suggestions = [];
      } finally {
        isSearching = false;
      }
    }, 300);

    return () => clearTimeout(timer);
  });

  onMount(() => {
    const handleClick = (e: MouseEvent) => {
      if (searchContainer && !searchContainer.contains(e.target as Node)) {
        showSuggestions = false;
      }
    };
    window.addEventListener("click", handleClick);
    return () => window.removeEventListener("click", handleClick);
  });
</script>

<svelte:window onscroll={handleScroll} />

<nav class="navbar" class:scrolled>
  <div class="nav-inner">
    <a href="/" class="logo">
      <span class="logo-text">ANIME<span class="logo-accent">PRO</span></span>
    </a>

    <div class="nav-links hide-mobile">
      {#each navLinks as link}
        <a
          href={link.href}
          class="nav-link"
          class:active={page.url.pathname === link.href}>{link.label}</a
        >
      {/each}
    </div>

    <div class="nav-actions">
      <button class="nav-icon-btn" onclick={handleRandom} title="Random Anime"
        >🎲</button
      >

      <div class="search-container" bind:this={searchContainer}>
        {#if searchOpen}
          <div class="search-box glass">
            <input
              type="text"
              placeholder="Search anime..."
              bind:value={searchQuery}
              onkeydown={handleSearch}
              onfocus={() => suggestions.length > 0 && (showSuggestions = true)}
            />
            {#if isSearching}
              <div class="search-spinner"></div>
            {/if}
            <button
              class="close-btn"
              onclick={() => {
                searchOpen = false;
                searchQuery = "";
                showSuggestions = false;
              }}>✕</button
            >
          </div>
        {:else}
          <button class="nav-icon-btn" onclick={() => (searchOpen = true)}
            >🔍</button
          >
        {/if}

        {#if showSuggestions && (suggestions.length > 0 || isSearching)}
          <div class="suggestions-dropdown glass">
            {#if isSearching && suggestions.length === 0}
              <div class="searching-state">Searching...</div>
            {:else}
              {#each suggestions as anime}
                <button
                  class="suggestion-item"
                  onclick={() => selectSuggestion(anime)}
                >
                  <img
                    src={getProxiedImage(anime.poster)}
                    alt={anime.title}
                    class="suggestion-poster"
                  />
                  <div class="suggestion-info">
                    <span class="suggestion-title">{anime.title}</span>
                    <div class="suggestion-meta">
                      <span class="suggestion-type">{anime.type}</span>
                      <span class="suggestion-score"
                        >⭐ {anime.score || "N/A"}</span
                      >
                    </div>
                  </div>
                </button>
              {/each}
            {/if}
          </div>
        {/if}
      </div>

      <button
        class="nav-icon-btn hamburger hide-desktop"
        onclick={() => (mobileMenuOpen = !mobileMenuOpen)}>☰</button
      >

      {#if $auth.user}
        <div class="user-profile">
          <button class="profile-trigger" title="Account">
            <img
              src={getProxiedImage(
                $auth.currentProfile?.avatar ||
                  `https://api.dicebear.com/7.x/avataaars/svg?seed=${$auth.user.email}`,
              )}
              alt="Profile"
            />
          </button>
          <div class="profile-dropdown glass">
            <div class="user-info">
              <span class="user-name"
                >{$auth.currentProfile?.name || "User"}</span
              >
              <span class="user-email">{$auth.user.email}</span>
            </div>
            <hr />
            <a href="/profile" class="dropdown-item">My Profile</a>
            <a href="/watchlist" class="dropdown-item">Watchlist</a>
            <a href="/favorites" class="dropdown-item">Favorites</a>
            <button
              class="dropdown-item logout"
              onclick={() => {
                logoutUser();
                goto("/");
              }}>Logout</button
            >
          </div>
        </div>
      {:else}
        <div class="auth-buttons hide-mobile">
          <a href="/auth/login" class="nav-btn-link">Login</a>
          <a href="/auth/register" class="nav-btn-link accent">Sign Up</a>
        </div>
      {/if}
    </div>
  </div>

  {#if mobileMenuOpen}
    <div class="mobile-menu glass">
      {#each navLinks as link}
        <a
          href={link.href}
          class="mobile-link"
          onclick={() => (mobileMenuOpen = false)}>{link.label}</a
        >
      {/each}
      {#if !$auth.user}
        <hr />
        <a
          href="/auth/login"
          class="mobile-link"
          onclick={() => (mobileMenuOpen = false)}>Login</a
        >
        <a
          href="/auth/register"
          class="mobile-link accent"
          onclick={() => (mobileMenuOpen = false)}>Sign Up</a
        >
      {/if}
    </div>
  {/if}
</nav>

<style>
  .navbar {
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    z-index: 1000;
    padding: 0.75rem 1rem;
    background: linear-gradient(
      180deg,
      rgba(0, 0, 0, 0.8) 0%,
      transparent 100%
    );
    transition: background 0.3s ease;
  }
  .navbar.scrolled {
    background: var(--net-bg);
    box-shadow: 0 4px 20px rgba(0, 0, 0, 0.3);
  }
  .nav-inner {
    display: flex;
    align-items: center;
    justify-content: space-between;
    max-width: 1400px;
    margin: 0 auto;
  }

  .logo {
    font-size: 1.4rem;
    font-weight: 800;
    letter-spacing: -0.03em;
    text-decoration: none;
    color: white;
  }
  .logo-accent {
    color: var(--net-red);
  }

  .nav-links {
    display: flex;
    gap: 1.5rem;
  }
  .nav-link {
    color: var(--net-text-muted);
    font-weight: 500;
    font-size: 0.95rem;
    transition: color 0.2s;
    text-decoration: none;
    padding: 0.5rem 0;
  }
  .nav-link:hover,
  .nav-link.active {
    color: white;
  }

  .nav-actions {
    display: flex;
    align-items: center;
    gap: 0.5rem;
  }
  .nav-icon-btn {
    color: white;
    font-size: 1.2rem;
    padding: 0.5rem;
    border-radius: 50%;
    transition: var(--transition);
    background: none;
    border: none;
    cursor: pointer;
    min-width: 44px;
    min-height: 44px;
    display: flex;
    align-items: center;
    justify-content: center;
  }
  .nav-icon-btn:hover {
    background: rgba(255, 255, 255, 0.1);
  }

  .search-container {
    position: relative;
  }
  .search-box {
    display: flex;
    align-items: center;
    background: rgba(40, 40, 40, 0.6);
    border: 1px solid rgba(255, 255, 255, 0.1);
    border-radius: var(--radius-md);
    padding: 0.4rem 0.8rem;
    gap: 0.5rem;
  }
  .search-box input {
    background: none;
    border: none;
    color: white;
    outline: none;
    font-size: 0.95rem;
    width: 180px;
  }

  .search-spinner {
    width: 14px;
    height: 14px;
    border: 2px solid rgba(255, 255, 255, 0.1);
    border-top-color: var(--net-red);
    border-radius: 50%;
    animation: spin 0.6s linear infinite;
  }
  @keyframes spin {
    to {
      transform: rotate(360deg);
    }
  }

  .close-btn {
    background: none;
    border: none;
    cursor: pointer;
    color: var(--net-text-muted);
    font-size: 0.9rem;
    padding: 4px;
    min-width: 32px;
    min-height: 32px;
  }

  .suggestions-dropdown {
    position: absolute;
    top: 115%;
    right: 0;
    width: 300px;
    max-width: calc(100vw - 2rem);
    border-radius: var(--radius-lg);
    box-shadow: 0 10px 40px rgba(0, 0, 0, 0.6);
    overflow: hidden;
    padding: 0.5rem;
    z-index: 1001;
  }

  .searching-state {
    padding: 1rem;
    text-align: center;
    color: var(--net-text-muted);
    font-size: 0.9rem;
  }

  .suggestion-item {
    display: flex;
    gap: 0.75rem;
    width: 100%;
    padding: 0.6rem;
    background: none;
    border: none;
    border-radius: var(--radius-md);
    cursor: pointer;
    text-align: left;
    transition: background 0.2s;
    min-height: 44px;
  }
  .suggestion-item:hover {
    background: rgba(255, 255, 255, 0.1);
  }

  .suggestion-poster {
    width: 40px;
    height: 56px;
    border-radius: 4px;
    object-fit: cover;
    background: #222;
    flex-shrink: 0;
  }
  .suggestion-info {
    display: flex;
    flex-direction: column;
    gap: 0.2rem;
    overflow: hidden;
    min-width: 0;
  }
  .suggestion-title {
    color: white;
    font-weight: 600;
    font-size: 0.9rem;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
  }
  .suggestion-meta {
    display: flex;
    gap: 0.5rem;
    font-size: 0.75rem;
    color: var(--net-text-muted);
  }
  .suggestion-score {
    color: #fbbf24;
  }

  .mobile-menu {
    display: flex;
    flex-direction: column;
    padding: 1rem;
    gap: 0.5rem;
    position: absolute;
    top: 100%;
    left: 0;
    right: 0;
    background: var(--net-bg);
    border-top: 1px solid rgba(255, 255, 255, 0.1);
    max-height: calc(100vh - 64px);
    overflow-y: auto;
    animation: slideDown 0.3s ease;
  }
  @keyframes slideDown {
    from {
      opacity: 0;
      transform: translateY(-10px);
    }
    to {
      opacity: 1;
      transform: translateY(0);
    }
  }
  .mobile-link {
    color: var(--net-text-muted);
    font-weight: 500;
    padding: 0.75rem 1rem;
    text-decoration: none;
    border-radius: var(--radius-md);
    transition: background 0.2s;
    min-height: 44px;
    display: flex;
    align-items: center;
  }
  .mobile-link:hover {
    background: rgba(255, 255, 255, 0.05);
    color: white;
  }
  .mobile-link.accent {
    color: var(--net-red);
    font-weight: 700;
  }

  .hide-mobile {
    display: none;
  }
  .hide-desktop {
    display: block;
  }
  @media (min-width: 768px) {
    .hide-mobile {
      display: flex;
    }
    .hide-desktop {
      display: none;
    }
    .navbar {
      padding: 0.75rem 2rem;
    }
    .logo {
      font-size: 1.6rem;
    }
    .search-box input {
      width: 220px;
    }
    .suggestions-dropdown {
      width: 320px;
    }
    .suggestion-poster {
      width: 44px;
      height: 62px;
    }
    .mobile-menu {
      padding: 1rem 2rem;
    }
  }
  .hamburger {
    font-size: 1.5rem;
  }

  .auth-buttons {
    display: flex;
    gap: 0.5rem;
    margin-left: 0.5rem;
  }
  .nav-btn-link {
    padding: 0.5rem 1rem;
    border-radius: 8px;
    font-size: 0.9rem;
    font-weight: 600;
    text-decoration: none;
    color: white;
    transition: 0.2s;
    min-height: 40px;
    display: flex;
    align-items: center;
  }
  .nav-btn-link:not(.accent):hover {
    background: rgba(255, 255, 255, 0.1);
  }
  .nav-btn-link.accent {
    background: var(--net-red);
  }
  .nav-btn-link.accent:hover {
    background: #ff1e2b;
    transform: translateY(-1px);
  }

  .user-profile {
    position: relative;
    margin-left: 0.5rem;
  }
  .profile-trigger {
    width: 36px;
    height: 36px;
    border-radius: 8px;
    overflow: hidden;
    border: 2px solid rgba(255, 255, 255, 0.1);
    cursor: pointer;
    padding: 0;
    transition: border-color 0.2s;
    min-width: 36px;
    min-height: 36px;
  }
  .profile-trigger:hover {
    border-color: var(--net-red);
  }
  .profile-trigger img {
    width: 100%;
    height: 100%;
    object-fit: cover;
  }

  .profile-dropdown {
    position: absolute;
    top: 120%;
    right: 0;
    width: 220px;
    max-width: calc(100vw - 2rem);
    border-radius: 12px;
    box-shadow: 0 10px 40px rgba(0, 0, 0, 0.5);
    opacity: 0;
    visibility: hidden;
    transform: translateY(-10px);
    transition: 0.2s cubic-bezier(0.165, 0.84, 0.44, 1);
    padding: 0.75rem;
    border: 1px solid rgba(255, 255, 255, 0.1);
  }
  .user-profile:hover .profile-dropdown {
    opacity: 1;
    visibility: visible;
    transform: translateY(0);
  }

  .user-info {
    display: flex;
    flex-direction: column;
    padding: 0.5rem;
  }
  .user-name {
    font-weight: 700;
    color: white;
    font-size: 0.95rem;
  }
  .user-email {
    font-size: 0.75rem;
    color: var(--net-text-muted);
  }

  hr {
    border: none;
    border-top: 1px solid rgba(255, 255, 255, 0.1);
    margin: 0.5rem 0;
  }
  .dropdown-item {
    display: block;
    width: 100%;
    text-align: left;
    padding: 0.6rem 0.8rem;
    border-radius: 8px;
    font-size: 0.9rem;
    color: var(--net-text-muted);
    text-decoration: none;
    background: none;
    border: none;
    cursor: pointer;
    transition: 0.2s;
    min-height: 40px;
  }
  .dropdown-item:hover {
    background: rgba(255, 255, 255, 0.05);
    color: white;
  }
  .dropdown-item.logout {
    color: #f87171;
  }
  .dropdown-item.logout:hover {
    background: rgba(248, 113, 113, 0.1);
  }

  /* Mobile-specific improvements */
  @media (max-width: 480px) {
    .navbar {
      padding: 0.6rem 0.75rem;
    }
    .logo {
      font-size: 1.2rem;
    }
    .nav-icon-btn {
      font-size: 1.1rem;
      padding: 0.4rem;
    }
    .search-box input {
      width: 140px;
      font-size: 0.9rem;
    }
    .suggestions-dropdown {
      width: calc(100vw - 1.5rem);
      right: -0.75rem;
      left: 0.75rem;
    }
    .suggestion-poster {
      width: 36px;
      height: 50px;
    }
    .profile-dropdown {
      width: 200px;
      right: -0.5rem;
    }
    .mobile-menu {
      padding: 0.75rem;
      max-height: calc(100vh - 56px);
    }
    .mobile-link {
      padding: 0.6rem 0.75rem;
      font-size: 0.95rem;
    }
  }

  @media (max-width: 360px) {
    .navbar {
      padding: 0.5rem 0.5rem;
    }
    .logo {
      font-size: 1.1rem;
    }
    .nav-icon-btn {
      font-size: 1rem;
      padding: 0.35rem;
      min-width: 40px;
      min-height: 40px;
    }
    .search-box input {
      width: 120px;
      font-size: 0.85rem;
    }
    .suggestions-dropdown {
      width: calc(100vw - 1rem);
      right: -0.5rem;
      left: 0.5rem;
    }
    .mobile-menu {
      padding: 0.5rem;
    }
    .mobile-link {
      padding: 0.5rem;
      font-size: 0.9rem;
    }
  }
</style>

// anime-pro/src/components/Navbar.tsx
import React, { useState, useEffect, useRef } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Search, Bell, User, X, Loader2 } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { animeAPI } from '../api/client';

const Navbar = () => {
  const [isScrolled, setIsScrolled] = useState(false);
  const [searchQuery, setSearchQuery] = useState('');
  const [searchOpen, setSearchOpen] = useState(false);
  const [suggestions, setSuggestions] = useState<any[]>([]);
  const [isSearching, setIsSearching] = useState(false);
  const [showSuggestions, setShowSuggestions] = useState(false);
  const navigate = useNavigate();
  const searchRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const handleScroll = () => setIsScrolled(window.scrollY > 0);
    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (searchRef.current && !searchRef.current.contains(event.target as Node)) {
        setShowSuggestions(false);
      }
    };
    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, []);

  // Debounced search suggestions using HiAnime search
  useEffect(() => {
    const timer = setTimeout(async () => {
      if (searchQuery.length >= 2) {
        setIsSearching(true);
        try {
          const response = await animeAPI.search(searchQuery);
          // DesiDubAnime response: { data: { results: [...] } }
          const animes: any[] = response.data?.data?.results || [];
          setSuggestions(animes.slice(0, 6));
          setShowSuggestions(true);
        } catch (error) {
          console.error('Search suggestions failed', error);
        } finally {
          setIsSearching(false);
        }
      } else {
        setSuggestions([]);
        setShowSuggestions(false);
      }
    }, 450);

    return () => clearTimeout(timer);
  }, [searchQuery]);

  const handleSearch = (e: React.FormEvent) => {
    e.preventDefault();
    if (searchQuery.trim()) {
      navigate(`/search?q=${encodeURIComponent(searchQuery)}`);
      setShowSuggestions(false);
      setSearchOpen(false);
    }
  };

  const selectSuggestion = (anime: any) => {
    navigate(`/anime/${anime.slug || anime.id}`);
    setSearchQuery('');
    setSearchOpen(false);
    setShowSuggestions(false);
  };

  return (
    <nav className={`navbar ${isScrolled ? 'scrolled' : ''}`} style={{
      position: 'fixed', top: 0, width: '100%', height: '70px', padding: '0 4%',
      display: 'flex', alignItems: 'center', justifyContent: 'space-between',
      transition: 'var(--transition)',
      backgroundColor: isScrolled ? 'var(--net-bg)' : 'transparent',
      backgroundImage: isScrolled ? 'none' : 'var(--net-gradient)',
      zIndex: 1000
    }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: '2.5rem' }}>
        <Link to="/" style={{ color: 'var(--net-red)', fontSize: '1.8rem', fontWeight: 800, letterSpacing: '-1px', display: 'flex', alignItems: 'center', gap: '4px' }}>
          ANIME<span style={{ color: 'white' }}>PRO</span>
        </Link>
        <div style={{ gap: '1.5rem', fontSize: '0.95rem', fontWeight: 500, display: window.innerWidth > 768 ? 'flex' : 'none' }}>
          <Link to="/" className="nav-link">Home</Link>
          <Link to="/latest" className="nav-link">Latest</Link>
          <Link to="/tv-series" className="nav-link">TV Shows</Link>
          <Link to="/movies" className="nav-link">Movies</Link>
          <Link to="/schedule" className="nav-link">Schedule</Link>
        </div>
      </div>

      <div style={{ display: 'flex', alignItems: 'center', gap: '1.5rem' }}>
        <div ref={searchRef} style={{ position: 'relative' }}>
          <form onSubmit={handleSearch} style={{
            display: 'flex', alignItems: 'center',
            background: searchOpen ? 'rgba(0,0,0,0.85)' : 'transparent',
            border: searchOpen ? '1px solid rgba(255,255,255,0.4)' : 'none',
            padding: searchOpen ? '6px 12px' : '0',
            borderRadius: '4px', transition: 'all 0.4s cubic-bezier(0.19, 1, 0.22, 1)',
            width: searchOpen ? '280px' : '32px'
          }}>
            <button type="button" onClick={() => setSearchOpen(!searchOpen)} style={{ color: 'white', display: 'flex', alignItems: 'center' }}>
              <Search size={22} />
            </button>
            <AnimatePresence>
              {searchOpen && (
                <motion.input initial={{ width: 0, opacity: 0 }} animate={{ width: '100%', opacity: 1 }} exit={{ width: 0, opacity: 0 }}
                  type="text" placeholder="Search anime..."
                  value={searchQuery} onChange={e => setSearchQuery(e.target.value)}
                  style={{ background: 'transparent', border: 'none', color: 'white', outline: 'none', marginLeft: '12px', fontSize: '0.9rem', width: '100%' }}
                  autoFocus />
              )}
            </AnimatePresence>
            {searchQuery && searchOpen && (
              <button onClick={() => setSearchQuery('')} type="button" style={{ color: 'var(--net-text-muted)' }}>
                {isSearching ? <Loader2 size={16} className="animate-spin" /> : <X size={16} />}
              </button>
            )}
          </form>

          {/* Suggestions dropdown */}
          <AnimatePresence>
            {showSuggestions && suggestions.length > 0 && (
              <motion.div initial={{ opacity: 0, y: 10, scale: 0.95 }} animate={{ opacity: 1, y: 0, scale: 1 }} exit={{ opacity: 0, y: 10, scale: 0.95 }}
                className="glass"
                style={{ position: 'absolute', top: '100%', right: 0, marginTop: '12px', width: '360px', borderRadius: '12px', overflow: 'hidden', boxShadow: '0 20px 40px rgba(0,0,0,0.6)', padding: '8px' }}>
                {suggestions.map(anime => (
                  <div key={anime.id} onClick={() => selectSuggestion(anime)}
                    style={{ display: 'flex', gap: '12px', padding: '10px', cursor: 'pointer', borderRadius: '8px', transition: 'var(--transition)' }}
                    className="suggestion-item"
                    onMouseEnter={e => (e.currentTarget.style.background = 'rgba(255,255,255,0.1)')}
                    onMouseLeave={e => (e.currentTarget.style.background = 'transparent')}>
                    <img src={anime.poster} alt={anime.title}
                      style={{ width: '48px', height: '68px', borderRadius: '4px', objectFit: 'cover', flexShrink: 0 }} />
                    <div style={{ display: 'flex', flexDirection: 'column', gap: '4px', overflow: 'hidden' }}>
                      <span className="line-clamp-1" style={{ fontWeight: 600, fontSize: '0.95rem', color: 'white' }}>
                        {anime.title}
                      </span>
                    </div>
                  </div>
                ))}
              </motion.div>
            )}
          </AnimatePresence>
        </div>

        <Bell size={22} style={{ color: 'white', cursor: 'pointer', display: window.innerWidth > 600 ? 'block' : 'none' }} />
        <div style={{ width: '34px', height: '34px', borderRadius: '4px', backgroundColor: 'var(--net-red)', display: 'flex', alignItems: 'center', justifyContent: 'center', cursor: 'pointer' }}>
          <User size={22} style={{ color: 'white' }} />
        </div>
      </div>
    </nav>
  );
};

export default Navbar;
