// sveltekit-frontend/src/lib/components/HeroBanner.svelte
<script lang="ts">
  import { getProxiedImage } from "$lib/api";
  import { onMount, onDestroy } from "svelte";
  import { goto } from "$app/navigation";

  let { items = [] } = $props<{ items: any[] }>();

  let current = $state(0);
  let paused = $state(false);
  let interval: ReturnType<typeof setInterval> | null = null;

  let touchStartX = $state(0);
  let touchEndX = $state(0);
  let isSwiping = $state(false);

  const heroes = $derived(
    items.filter((a: any) => a.image || a.poster).slice(0, 8),
  );

  function next() {
    current = (current + 1) % heroes.length;
  }
  function prev() {
    current = (current - 1 + heroes.length) % heroes.length;
  }
  function goTo(i: number) {
    current = i;
  }

  function startAutoplay() {
    stopAutoplay();
    interval = setInterval(() => {
      if (!paused) next();
    }, 3000);
  }
  function stopAutoplay() {
    if (interval) clearInterval(interval);
  }

  function handleTouchStart(e: TouchEvent) {
    touchStartX = e.changedTouches[0].screenX;
    isSwiping = true;
    paused = true;
  }
  function handleTouchMove(e: TouchEvent) {
    if (!isSwiping) return;
    touchEndX = e.changedTouches[0].screenX;
  }
  function handleTouchEnd() {
    if (!isSwiping) return;
    isSwiping = false;
    paused = false;
    const diff = touchStartX - touchEndX;
    if (Math.abs(diff) > 50) {
      diff > 0 ? next() : prev();
      startAutoplay();
    }
  }

  onMount(startAutoplay);
  onDestroy(stopAutoplay);

  const anime = $derived(heroes[current]);
  const poster = $derived(getProxiedImage(anime?.image || anime?.poster || ""));
  const title = $derived(anime?.title || "Unknown");
  const synopsis = $derived((anime?.synopsis || "").replace(/<[^>]*>?/gm, ""));
  const genres = $derived(anime?.genres || []);
  const id = $derived(anime?.id || anime?.mal_id);
  const rawScore = $derived(anime?.score || anime?.rating || 0);
  const score = $derived(rawScore > 10 ? rawScore / 10 : rawScore);
  const year = $derived(anime?.year || anime?.aired?.from?.split("-")[0] || "");
  const format = $derived(anime?.type || anime?.format || "");
  const episodes = $derived(anime?.episodes || anime?.totalEpisodes || 0);

  function handlePlay(e?: Event) {
    if (e instanceof MouseEvent && (e.button === 1 || e.ctrlKey || e.metaKey)) return;
    if (e) e.preventDefault();
    if (id) goto(`/watch/${id}/1`);
  }
  function handleDetails(e?: Event) {
    if (e instanceof MouseEvent && (e.button === 1 || e.ctrlKey || e.metaKey)) return;
    if (e) e.preventDefault();
    if (id) goto(`/anime/${id}`);
  }
  function handleKeydown(fn: Function) {
    return (e: KeyboardEvent) => { if (e.key === 'Enter') fn(e); };
  }
</script>

{#if heroes.length > 0}
  <section
    class="hero"
    aria-label="Featured anime carousel"
    onmouseenter={() => (paused = true)}
    onmouseleave={() => (paused = false)}
    ontouchstart={handleTouchStart}
    ontouchmove={handleTouchMove}
    ontouchend={handleTouchEnd}
  >
    {#each heroes as slide, i}
      <div
        class="hero-bg"
        class:active={i === current}
        style={(i === current ||
          i === (current + 1) % heroes.length ||
          i === (current - 1 + heroes.length) % heroes.length)
          ? `background-image: url(${getProxiedImage(slide.image || slide.poster || '')});`
          : ''}
      ></div>
    {/each}

    <div class="hero-gradient"></div>

    <div class="hero-content">
      {#if genres.length > 0}
        <p class="hero-genres">{genres.slice(0, 3).join('   •   ')}</p>
      {/if}

      <h1 class="hero-title">{title}</h1>

      <div class="hero-meta">
        {#if score > 0}<span class="meta-score">★ {score.toFixed(1)}</span>{/if}
        {#if year}<span class="meta-item">{year}</span>{/if}
        {#if format}<span class="meta-item">{format}</span>{/if}
        {#if episodes > 0}<span class="meta-item">{episodes} eps</span>{/if}
      </div>

      {#if synopsis}
        <p class="hero-desc">{synopsis.slice(0, 180)}{synopsis.length > 180 ? '...' : ''}</p>
      {/if}

      <div class="hero-actions">
        <a href="/watch/{id}/1" class="btn-hero-primary" role="button" tabindex="0" onclick={handlePlay} onkeydown={handleKeydown(handlePlay)}>▶ Play</a>
        <a href="/anime/{id}" class="btn-hero-secondary" role="button" tabindex="0" onclick={handleDetails} onkeydown={handleKeydown(handleDetails)}>ℹ Details</a>
      </div>
    </div>

    <button class="hero-arrow left" onclick={prev} aria-label="Previous">‹</button>
    <button class="hero-arrow right" onclick={next} aria-label="Next">›</button>

    <div class="hero-dots">
      {#each heroes as _, i}
        <button
          class="dot"
          class:active={i === current}
          onclick={() => goTo(i)}
          aria-label="Slide {i + 1}"
        >
          <span class="dot-track">
            {#if i === current}
              <span class="dot-progress"></span>
            {/if}
          </span>
        </button>
      {/each}
    </div>
  </section>
{/if}

<style>
  .hero {
    position: relative;
    width: 100%;
    height: 65vh;
    min-height: 480px;
    overflow: hidden;
    display: flex;
    align-items: flex-end;
    touch-action: pan-y;
    user-select: none;
    -webkit-user-select: none;
  }

  .hero-bg {
    position: absolute;
    inset: 0;
    background-size: cover;
    background-position: center top;
    opacity: 0;
    transform: scale(1.03);
    transition:
      opacity 0.8s cubic-bezier(0.4, 0, 0.2, 1),
      transform 6s cubic-bezier(0.4, 0, 0.2, 1);
  }
  .hero-bg.active {
    opacity: 1;
    transform: scale(1);
  }

  .hero-gradient {
    position: absolute;
    inset: 0;
    z-index: 1;
    background:
      linear-gradient(to top, var(--net-bg) 0%, rgba(10,10,10,0.7) 40%, rgba(10,10,10,0.15) 100%),
      linear-gradient(to right, rgba(10,10,10,0.75) 0%, transparent 55%);
  }

  .hero-content {
    position: relative;
    z-index: 3;
    padding: 2.5rem 3rem;
    padding-bottom: 3.5rem;
    max-width: 700px;
  }

  .hero-genres {
    color: rgba(255, 255, 255, 0.7);
    font-weight: 700;
    font-size: 0.85rem;
    letter-spacing: 0.5px;
    margin-bottom: 0.6rem;
  }

  .hero-title {
    font-size: clamp(1.8rem, 4.5vw, 3rem);
    font-weight: 900;
    letter-spacing: -0.03em;
    line-height: 1.05;
    margin-bottom: 0.6rem;
    text-shadow: 0 4px 16px rgba(0, 0, 0, 0.5);
  }

  .hero-meta {
    display: flex;
    align-items: center;
    gap: 0;
    margin-bottom: 0.7rem;
    font-size: 0.82rem;
    color: #a3a3a3;
    font-weight: 500;
  }
  .hero-meta .meta-score {
    color: #fbbf24;
    font-weight: 700;
  }
  .hero-meta .meta-item::before,
  .hero-meta .meta-score + .meta-item::before {
    content: "•";
    margin: 0 0.5rem;
    color: #a3a3a3;
  }
  .hero-meta .meta-item:first-child::before {
    display: none;
  }

  .hero-desc {
    color: #a3a3a3;
    font-size: 0.9rem;
    line-height: 1.5;
    margin-bottom: 1.2rem;
    max-width: 480px;
  }

  .hero-actions {
    display: flex;
    gap: 0.75rem;
    flex-wrap: wrap;
  }

  .btn-hero-primary {
    display: inline-flex;
    align-items: center;
    gap: 0.4rem;
    background: white;
    color: black;
    font-weight: 700;
    font-size: 0.95rem;
    padding: 0.7rem 1.6rem;
    border-radius: 8px;
    text-decoration: none;
    transition: transform 0.2s ease, background 0.2s ease;
  }
  .btn-hero-primary:hover {
    transform: scale(1.05);
    background: rgba(255, 255, 255, 0.9);
  }
  .btn-hero-primary:focus-visible {
    outline: 3px solid white;
    outline-offset: 3px;
  }

  .btn-hero-secondary {
    display: inline-flex;
    align-items: center;
    gap: 0.4rem;
    background: rgba(255, 255, 255, 0.12);
    color: white;
    font-weight: 700;
    font-size: 0.95rem;
    padding: 0.7rem 1.6rem;
    border-radius: 8px;
    text-decoration: none;
    transition: transform 0.2s ease, background 0.2s ease;
  }
  .btn-hero-secondary:hover {
    background: rgba(255, 255, 255, 0.2);
    transform: scale(1.05);
  }
  .btn-hero-secondary:focus-visible {
    outline: 3px solid white;
    outline-offset: 3px;
  }

  /* Arrows */
  .hero-arrow {
    position: absolute;
    top: 50%;
    transform: translateY(-50%);
    z-index: 5;
    width: 44px;
    height: 72px;
    background: rgba(0, 0, 0, 0.3);
    backdrop-filter: blur(4px);
    border: 1px solid rgba(255, 255, 255, 0.08);
    border-radius: 8px;
    color: white;
    font-size: 1.8rem;
    display: flex;
    align-items: center;
    justify-content: center;
    cursor: pointer;
    opacity: 0;
    transition: all 0.3s ease;
  }
  .hero:hover .hero-arrow {
    opacity: 1;
  }
  .hero-arrow:hover {
    background: rgba(255, 255, 255, 0.15);
    border-color: rgba(255, 255, 255, 0.2);
  }
  .hero-arrow.left { left: 1rem; }
  .hero-arrow.right { right: 1rem; }

  /* Dots */
  .hero-dots {
    position: absolute;
    bottom: 1rem;
    left: 50%;
    transform: translateX(-50%);
    z-index: 5;
    display: flex;
    gap: 0.4rem;
  }
  .dot {
    width: 40px;
    height: 40px;
    display: flex;
    align-items: center;
    justify-content: center;
    background: transparent;
    cursor: pointer;
    border: none;
    padding: 0;
  }
  .dot-track {
    width: 28px;
    height: 3px;
    border-radius: 2px;
    background: rgba(255, 255, 255, 0.25);
    overflow: hidden;
    position: relative;
    display: block;
    transition: width 0.3s ease;
  }
  .dot:hover .dot-track {
    background: rgba(255, 255, 255, 0.5);
  }
  .dot.active .dot-track {
    width: 40px;
    background: rgba(255, 255, 255, 0.2);
  }
  .dot-progress {
    position: absolute;
    inset: 0;
    background: white;
    border-radius: 2px;
    transform-origin: left;
    animation: dot-fill 4s linear forwards;
  }
  @keyframes dot-fill {
    from { transform: scaleX(0); }
    to { transform: scaleX(1); }
  }

  /* Mobile */
  @media (max-width: 768px) {
    .hero {
      height: 45vh;
      min-height: 300px;
    }
    .hero-content {
      padding: 1.5rem 1.25rem;
      padding-bottom: 4rem;
    }
    .hero-arrow { display: none; }
    .hero-title { font-size: clamp(1.3rem, 6vw, 2rem); }
    .hero-genres { font-size: 0.75rem; margin-bottom: 0.4rem; }
    .hero-meta { font-size: 0.75rem; }
    .hero-desc {
      font-size: 0.8rem;
      display: -webkit-box;
      -webkit-line-clamp: 2;
      line-clamp: 2;
      -webkit-box-orient: vertical;
      overflow: hidden;
      margin-bottom: 0.8rem;
    }
    .hero-actions { gap: 0.5rem; }
    .btn-hero-primary,
    .btn-hero-secondary {
      padding: 0.55rem 1.1rem;
      font-size: 0.85rem;
    }
    .hero-dots { bottom: 0.7rem; }
    .dot { width: 30px; height: 30px; }
    .dot-track { width: 18px; height: 2.5px; }
    .dot.active .dot-track { width: 28px; }
  }

  @media (max-width: 480px) {
    .hero {
      height: 42vh;
      min-height: 270px;
    }
    .hero-content {
      padding: 1rem 0.85rem;
      padding-bottom: 3.5rem;
    }
    .hero-title { font-size: clamp(1.1rem, 7vw, 1.6rem); }
    .hero-genres { font-size: 0.7rem; }
    .hero-desc {
      font-size: 0.75rem;
      -webkit-line-clamp: 2;
      line-clamp: 2;
    }
    .hero-actions { flex-direction: row; width: 100%; }
    .btn-hero-primary,
    .btn-hero-secondary {
      flex: 1;
      justify-content: center;
      padding: 0.5rem 0.8rem;
      font-size: 0.8rem;
    }
    .hero-dots { bottom: 0.5rem; }
    .dot { width: 26px; height: 26px; }
    .dot-track { width: 14px; height: 2px; }
    .dot.active .dot-track { width: 22px; }
  }
</style>

// jikan-frontend/src/components/HeroBanner.tsx
import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { Play, Info, ChevronLeft, ChevronRight, Calendar, Clock, Tv } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { ScoreBadge, QualityBadge, StatusBadge } from './Badge';

interface HeroBannerProps {
  anime: any;
  animeList?: any[];
}

const HeroBanner: React.FC<HeroBannerProps> = ({ anime, animeList }) => {
  const [currentIndex, setCurrentIndex] = useState(0);
  const [isPaused, setIsPaused] = useState(false);

  // Use provided list or create a single-item array
  const animeArray = animeList && animeList.length > 0 ? animeList : (anime ? [anime] : []);

  const currentAnime = animeArray[currentIndex] || anime;

  useEffect(() => {
    if (animeArray.length <= 1 || isPaused) return;

    const interval = setInterval(() => {
      setCurrentIndex((prev) => (prev + 1) % animeArray.length);
    }, 8000); // Change every 8 seconds

    return () => clearInterval(interval);
  }, [animeArray.length, isPaused]);


  const handlePrevious = () => {
    setCurrentIndex((prev) => (prev - 1 + animeArray.length) % animeArray.length);
  };

  const handleNext = () => {
    setCurrentIndex((prev) => (prev + 1) % animeArray.length);
  };

  if (!currentAnime) return (
    <div style={{ height: '80vh', backgroundColor: 'var(--net-bg)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
      <motion.div
        animate={{ scale: [1, 1.1, 1] }}
        transition={{ repeat: Infinity, duration: 2 }}
        className="text-red"
        style={{ fontSize: '2rem', fontWeight: 800 }}
      >
        ANIME PRO
      </motion.div>
    </div>
  );

  const backgroundImageUrl = currentAnime.poster || currentAnime.image || '';
  const title = currentAnime.title || 'Unknown Title';
  const titleEnglish = currentAnime.title_english || '';
  const score = currentAnime.rating || currentAnime.score || 0;
  const episodes = currentAnime.episodes || 0;
  const genres = currentAnime.genres || [];

  return (
    <header
      style={{
        color: 'white',
        height: 'clamp(60vh, 85vh, 90vh)',
        width: '100%',
        position: 'relative',
        overflow: 'hidden',
        minHeight: '400px'
      }}
      onMouseEnter={() => setIsPaused(true)}
      onMouseLeave={() => setIsPaused(false)}
    >
      <AnimatePresence mode="wait">
        <motion.div
          key={currentIndex}
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          transition={{ duration: 1, ease: "easeInOut" }}
          style={{
            position: 'absolute',
            top: 0, left: 0, right: 0, bottom: 0,
            backgroundImage: `url("${backgroundImageUrl}")`,
            backgroundSize: 'cover',
            backgroundPosition: 'center 20%',
            zIndex: 0
          }}
        />
      </AnimatePresence>

      {/* Gradients */}
      <div style={{
        position: 'absolute',
        top: 0, left: 0, right: 0, bottom: 0,
        background: 'linear-gradient(90deg, rgba(10, 10, 10, 0.9) 0%, rgba(10, 10, 10, 0.5) 40%, transparent 80%)',
        zIndex: 1
      }} />
      <div style={{
        position: 'absolute',
        bottom: 0, left: 0, right: 0,
        height: '40%',
        background: 'var(--net-footer-gradient)',
        zIndex: 2
      }} />

      {/* Navigation arrows */}
      {animeArray.length > 1 && (
        <>
          <button
            onClick={handlePrevious}
            style={{
              position: 'absolute',
              left: 'clamp(1rem, 4vw, 4%)',
              top: '50%',
              transform: 'translateY(-50%)',
              zIndex: 20,
              backgroundColor: 'rgba(0,0,0,0.5)',
              border: 'none',
              borderRadius: '50%',
              width: 'clamp(36px, 5vw, 48px)',
              height: 'clamp(36px, 5vw, 48px)',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              cursor: 'pointer',
              transition: 'all 0.3s ease'
            }}
            onMouseEnter={(e: React.MouseEvent<HTMLButtonElement>) => e.currentTarget.style.backgroundColor = 'rgba(0,0,0,0.8)'}
            onMouseLeave={(e: React.MouseEvent<HTMLButtonElement>) => e.currentTarget.style.backgroundColor = 'rgba(0,0,0,0.5)'}
          >
            <ChevronLeft size={24} />
          </button>
          <button
            onClick={handleNext}
            style={{
              position: 'absolute',
              right: '4%',
              top: '50%',
              transform: 'translateY(-50%)',
              zIndex: 20,
              backgroundColor: 'rgba(0,0,0,0.5)',
              border: 'none',
              borderRadius: '50%',
              width: 'clamp(36px, 5vw, 48px)',
              height: 'clamp(36px, 5vw, 48px)',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              cursor: 'pointer',
              transition: 'all 0.3s ease'
            }}
            onMouseEnter={(e: React.MouseEvent<HTMLButtonElement>) => e.currentTarget.style.backgroundColor = 'rgba(0,0,0,0.8)'}
            onMouseLeave={(e: React.MouseEvent<HTMLButtonElement>) => e.currentTarget.style.backgroundColor = 'rgba(0,0,0,0.5)'}
          >
            <ChevronRight size={24} />
          </button>

          {/* Dots indicator */}
          <div style={{
            position: 'absolute',
            bottom: '20%',
            left: '4%',
            zIndex: 20,
            display: 'flex',
            gap: '8px'
          }}>
            {animeArray.map((_, idx) => (
              <button
                key={idx}
                onClick={() => setCurrentIndex(idx)}
                style={{
                  width: idx === currentIndex ? '24px' : '8px',
                  height: '8px',
                  borderRadius: '4px',
                  backgroundColor: idx === currentIndex ? 'var(--net-red)' : 'rgba(255,255,255,0.4)',
                  border: 'none',
                  cursor: 'pointer',
                  transition: 'all 0.3s ease'
                }}
              />
            ))}
          </div>
        </>
      )}

      <div className="container" style={{ position: 'relative', height: '100%', display: 'flex', flexDirection: 'column', justifyContent: 'center', zIndex: 10, paddingTop: '5rem' }}>
        <AnimatePresence mode="wait">
          <motion.div
            key={currentAnime.id || currentIndex}
            initial={{ opacity: 0, x: -30 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: 30 }}
            transition={{ duration: 0.8, ease: "easeOut" }}
          >
            {currentAnime.isDub && (
              <motion.span
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.3 }}
                className="bg-red"
                style={{
                  fontSize: '0.85rem',
                  fontWeight: 700,
                  padding: '4px 12px',
                  borderRadius: '4px',
                  display: 'inline-block',
                  marginBottom: '1rem'
                }}
              >
                HINDI DUBBED
              </motion.span>
            )}

            <h1 className="line-clamp-2" style={{
              fontSize: 'min(5rem, 10vw)',
              fontWeight: 800,
              lineHeight: 1.1,
              maxWidth: '650px',
              marginBottom: currentAnime.synopsis ? '0.5rem' : '1.5rem',
              textShadow: '0 4px 12px rgba(0,0,0,0.5)',
              letterSpacing: '-0.03em'
            }}>
              {title}
            </h1>

            {titleEnglish && titleEnglish !== title && (
              <motion.p
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ delay: 0.4 }}
                style={{
                  fontSize: '1.2rem',
                  color: 'rgba(255,255,255,0.7)',
                  marginBottom: '1rem',
                  fontStyle: 'italic'
                }}
              >
                {titleEnglish}
              </motion.p>
            )}

            {/* Meta info */}
            <motion.div
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.5 }}
              style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', marginBottom: '1rem', flexWrap: 'wrap' }}
            >
              {score > 0 && <ScoreBadge score={score} size="lg" />}
              <QualityBadge quality="HD" size="lg" />
              {currentAnime.status && <StatusBadge status={currentAnime.status as any} size="lg" />}
              {episodes > 0 && (
                <span style={{
                  display: 'flex',
                  alignItems: 'center',
                  gap: '0.35rem',
                  color: 'white',
                  fontSize: '0.9rem',
                  fontWeight: 600,
                  padding: '0.35rem 0.7rem',
                  backgroundColor: 'rgba(255,255,255,0.1)',
                  borderRadius: '4px'
                }}>
                  <Tv size={16} /> {episodes} Episodes
                </span>
              )}
              {currentAnime.duration && (
                <span style={{
                  display: 'flex',
                  alignItems: 'center',
                  gap: '0.35rem',
                  color: 'rgba(255,255,255,0.8)',
                  fontSize: '0.85rem',
                  padding: '0.35rem 0.7rem',
                  backgroundColor: 'rgba(255,255,255,0.05)',
                  borderRadius: '4px'
                }}>
                  <Clock size={14} /> {currentAnime.duration}
                </span>
              )}
              {currentAnime.year && (
                <span style={{
                  display: 'flex',
                  alignItems: 'center',
                  gap: '0.35rem',
                  color: 'rgba(255,255,255,0.8)',
                  fontSize: '0.85rem',
                  padding: '0.35rem 0.7rem',
                  backgroundColor: 'rgba(255,255,255,0.05)',
                  borderRadius: '4px'
                }}>
                  <Calendar size={14} /> {currentAnime.year}
                </span>
              )}
            </motion.div>

            {/* Genres */}
            {genres.length > 0 && (
              <motion.div
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.55 }}
                style={{ display: 'flex', gap: '0.5rem', marginBottom: '1rem', flexWrap: 'wrap' }}
              >
                {genres.slice(0, 4).map((genre: any) => (
                  <span key={typeof genre === 'string' ? genre : genre.name} style={{
                    fontSize: '0.8rem',
                    padding: '0.3rem 0.7rem',
                    backgroundColor: 'rgba(229, 9, 20, 0.2)',
                    border: '1px solid rgba(229, 9, 20, 0.4)',
                    color: '#E50914',
                    borderRadius: '20px',
                    fontWeight: 600
                  }}>
                    {typeof genre === 'string' ? genre : genre.name}
                  </span>
                ))}
              </motion.div>
            )}

            {currentAnime.synopsis && currentAnime.synopsis !== 'No description available.' && (
              <motion.p
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ delay: 0.6 }}
                className="line-clamp-3"
                style={{
                  maxWidth: '600px',
                  fontSize: '1.05rem',
                  color: 'rgba(255,255,255,0.85)',
                  lineHeight: '1.5',
                  textShadow: '0 2px 4px rgba(0,0,0,0.8)',
                  marginBottom: '1.5rem',
                  marginTop: '1rem'
                }}
              >
                {currentAnime.synopsis}
              </motion.p>
            )}

            <motion.div
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.7 }}
              style={{ display: 'flex', gap: '1.25rem', marginTop: '2rem' }}
            >
              <Link to={`/watch/${currentAnime.id}/1`}>
                <button className="btn-primary">
                  <Play fill="black" size={24} /> Play Now
                </button>
              </Link>
              <Link to={`/anime/${currentAnime.id}`}>
                <button className="btn-secondary">
                  <Info size={24} /> More Info
                </button>
              </Link>
            </motion.div>
          </motion.div>
        </AnimatePresence>
      </div>
    </header>
  );
};

export default HeroBanner;
